invalid_driver_city =[
        "ADOLF-FRAAB-STR 12",
        "20906",
        "6CL1286",
        "7600 MAPLE AVE APT 1",
        "19033 GROTTO LN",
        "APT 933 COLUMBIA",
        "APT 12",
        "MONROE TWP.",
        "19405 BATTLERIDGE WY",
        "TOWN & COUNTRY",
        "1ST ST NW UNIT S",
        "ITIN ST #2",
        "M-635-108-319-042",
        "2129 CLARK PL", 
        "GREGORY ST.",
        "nan"
        "ONEY",
        "BOWE",
        "NONE",
        "BOYS",
        "WASH",
        "ELON",
        "OLNE",
        "EGAN",
        "LANH",
        "GOLT",
        "ROCK",
        "JBER",
        "CLYO",
        "GERM",
        "GATH",
        "AJAX",
        "CADE",
        "LUKE",
        "ALDI",
        "CAEN",
        "IOTA",
        "YIGO",
        "ETNA",
        "XXXX",
        "TEST",
        "HEAD"
    ]

prefix_mapping = {
    r"^N\.?\s+": "NORTH ",
    r"^S\.?\s+": "SOUTH ",
    r"^E\.?\s+": "EAST ",
    r"^W\.?\s+": "WEST ",
    r"^NO\.?\s+": "NORTH ",
    r"^MT\.?\s*": "MOUNT ",
    r"^FT\.?\s+": "FORT ",
    r"^ST\.?\s+": "SAINT ",
    r"^DIST\.?\s+": "DISTRICT ",
    r"^MONT\.?\s+": "MONTGOMERY "
}