invalid_make = [
    "WSTR",
    "TSMR",
    "HAWK",
    "FLY WING",
    "TRANSPRO",
    "KAUFMAN",
    "ZHEJIANG JIAJUE",
    "TAIZOU",
    "GILG",
    "RAN",
    "ZR900",
    "UT",
    "OTH",
    "TRLR",
    "TAIZHOU",
    "ZHEJIANG",
    "WEST",
    "SALVAGE",
    "BUDDY",
    "JIAJUE",
    "LAMO",
    "COTC",
    "QUALITY",
    "UNKNOWN",
    "STRN",
    "SOLAR",
    "JANUS",
    "MAST",
    "HITE",
    "YONGFU",
    "TAIZHOU ZHONGEN",
    "QIAN",
    "THMS",
    "STLG",
    "KAWK",
    "JIAJU",
    "HOMESTEADER TRL",
    "SURE",
    "YOUNGFU",
    "STER",
    "ZHLONG",
    "TRANSPORT",
    "CARRIE ON",
    "MOPED",
    "SILVER",
    "LEGE",
    "JIAJ",
    "AMSTAR",
    "PACE",
    "CARRY ON T",
    "MIFU",
    "CATTY",
    "SOLANA",
    "AN",
    "RIVA",
    "GR",
    "PACE SPORTS",
    "ITALIAN",
    "YIBEN",
    "USPS",
    "2023",
    "RDKG",
    "MARSHALL",
    "UTIL",
    "SPRI",
    "WANC",
    "2012",
    "STRG",
    "SPAL",
    "ERZ",
    "PEACE SPORT",
    "EGIL",
    "ZHILONG",
    "MIO 50",
    "TZTC",
    "ZHONGNENG",
    "GRAY",
    "SCOOTER",
    "AALI",
    "APOL",
    "X-PRO",
    "TAIZHOU ZHILONG",
    "TAIZHOU ZHONGNE",
    "CARR",
    "SANMEN",
    "BAODIAO",
    "ZNEN",
    "DONG FANG",
    "GRAND",
    "NINGBO",
    "BRAN",
    "TRANS PRO",
    "TAIZHOU QIANXIN",
    "H",
    "2011",
    "GATOR",
    "QIANXIN",
    "KRAFTSMAN",
    "ITALICA",
    "UNKOWN",
    "ZHNG",
    "ZHIL",
    "FLYWING",
    "MCI",
    "TAIZ",
    "CLASH",
    "BIGT",
    "EPO",
    "DUMP",
    "2016",
    "9EC5338",
    "TAIWAN GOLDEN B",
    "HUZH",
    "EZDU",
    "ETO",
    "MOTOR SCOOTER",
    "GOLDEN BEE",
    "BRI MAR",
    "GILL",
    "FTR",
    "SEDAN",
    "PREM",
    "1GCHG39U9312199",
    "BLUE",
    "ELGI",
    "2T3ZFREV5FW2069",
    "BRMR",
    "CAI",
    "NEW FLUER",
    "1N4BA41E35C8089",
    "2007",
    "HOME",
    "ORIO",
    "EXTREME",
    "GIO",
    "NUS",
    "nan",
    "RIYA",
    "RIDE ON",
    "4S",
    "LOAD",
    "6BR9831",
    "MIST",
    "RIDEON",
    "CRNE",
    "LARO",
    "3FNY97",
    "NONE LISTED",
    "COPPER",
    "CAMA",
    "COLEMAN",
    "UD",
    "BRMA",
    "NIMR",
    "MEBE",
    "MOTOBRAVO",
    "DASH",
    "2AC9011",
    "KING RING",
    "ESCO",
    "EADU",
    "KIW",
    "SHANGHAI",
    "1J4GR48K46C1478",
    "MC",
    "UHAUL",
    "SOUT",
    "PREMIER",
    "FANGYUE",
    "PIER SPEED",
    "JIFF",
    "HOMEMADE",
    "GLAV",
    "LEONARD",
    "DONGFANG",
    "BASH",
    "IA",
    "CAM",
    "JA32W8FV1DU0176",
    "E-TON BEAMER",
    "PERO",
    "4D",
    "CARRY",
    "GORRILLA",
    "APOLLO",
    "KNAFU6A29B54609",
    "WORK",
    "TMSR",
    "JONWAY",
    "HYTR",
    "ERL",
    "XINGYUE",
    "UTILITY",
    "METROPOLITAN",
    "ROAD",
    "STAR",
    "SHORELANDER",
    "INTEL",
    "FLY SCOOTER",
    "NT",
    "TYN",
    "A",
    "HENSIM",
    "DELRAY",
    "UNK",
    "LEIKE",
    "MONGOOSE",
    "DONG",
    "EZLO",
    "APPOLO",
    "TAGA",
    "DYKON",
    "ORION",
    "ROD",
    "SUPERIOR",
    "FUJI",
    "TAIZHOU CHUANL",
    "CARGO",
    "AURA",
    "VIP",
    "GMX",
    "QUALITY STEEL",
    "ATV",
    "AUTO",
    "KA",
    "36V663",
    "FELT",
    "XX",
    "EM",
    "TAIW",
    "PEDESTRIAN",
    "BAJA",
    "STAR TRANS",
    "SURE-TRAC",
    "BADO",
    "6BX9543",
    "TATT",
    "BOOM",
    "FLORIDA",
    "5NMS5CAAXLH2313",
    "TEXTTRON",
    "NONE",
    "NDMC",
    "VPG",
    "YONFU",
    "KM",
    "WRKH",
    "CHONGOING",
    "VULC",
    "2000",
    "LIEKE",
    "WHITE",
    "ZHEJIANG TAOTAO",
    "ZUMMERQ",
    "TOU",
    "MAKE",
    "2002",
    "XXXX",
    "GMG",
    "RED",
    "2S",
    "UU",
    "2006",
    "FEDEX",
    "BLACK",
    "MAROON",
    "TREX",
    "REDLINE",
    "2HGFC2F76GH5421",
    "2014",
    "CHAN",
    "BARCH",
    "TYG",
    "LE",
    "4X4",
    "GRAND TENTON",
    "LLV",
    "JEFF",
    "SI",
    "CALI",
    "LEIK",
    "DODGECHEVY",
    "DF4958",
    "SHUTTLE BUS",
    "MOTORELI",
    "WORT",
    "MOTRA",
    "SUPERHORNET",
    "HUMAN BEING",
    "AMERICANA",
    "PEACE SPORTS",
    "MOTIVE",
    "NINMBO",
    "ONEA",
    "TCS DYKON",
    "GOLD",
    "CCC",
    "GREEN POWER",
    "2010",
    "4DR",
    "SNOW BEAR",
    "TK",
    "HMC",
    "NP",
    "GOSH",
    "CRANE CARRIER",
    "LANCASTER",
    "VACR",
    "LANCE",
    "HUMAN-BEING",
    "HEIL",
    "ACAD",
    "UNITED STATES",
    "CRRY",
    "CARRY ON",
    "LODA",
    "BECK",
    "NC",
    "CRAN",
    "SUPER HORNET",
    "BOX",
    "ZHEJIANG JONWAY",
    "KENWOOD",
    "SKY INC",
    "BRECHBILL",
    "EPD",
    "PT",
    "FLASH",
    "HERCHEE",
    "BART",
    "XIAMEN XIASHING",
    "KINC",
    "FABRIQUE",
    "SE",
    "BELM",
    "RUC",
    "HAUL",
    "BUS",
    "BIG TEX",
    "CRISWELL",
    "QIPAI",
    "STELLA",
    "PERS",
    "MOTOR",
    "PENSKE",
    "QIYE",
    "HOMESTEADER",
    "PROS",
    "BGTX",
    "2004",
    "ZHILONG TECH",
    "KAIT",
    "GT",
    "FREIGHT HAULER",
    "OTHR",
    "JH4DB7656WS0073",
    "IC",
    "2DR",
    "QUALITY TRAILER",
    "AMER",
    "VPG/U NAME IT",
    "SHOR",
    "TARTER",
    "JMST",
    "HOME STAR",
    "JAMIS",
    "KAUF",
    "TOMO",
    "TBU",
    "FACE",
    "MINIBIKE",
    "1FADP3F2XDL1682",
    "SPEED",
    "1HGCR2F16HA2204",
    "SLIN",
    "WDBUF76J25A6414",
    "3",
    "KEMP",
    "KEEP",
    "FCA",
    "KALW",
    "CRCA",
    "V",
    "AMO",
    "WHIT",
    "CHEN",
    "2019",
    "PETREBUILD",
    "POSH",
    "BIKE",
    "NOVB",
    "NOND",
    "BRIM",
    "RAZOR",
    "MASTER",
    "ANVIL TRAILER",
    "FPHT",
    "FLYER",
    "MCIN",
    "MAC",
    "RIDE",
    "CONT",
    "KRYSTAL",
    "TAKE",
    "1D7HA18D54S7413",
    "7BG6353",
    "RIDGE",
    "GENUINE",
    "KOEHRING",
    "SUPE",
    "GDAN",
    "RAVE",
    "BICYCLE",
    "TRUCK",
    "NXH110",
    "TR",
    "JIA",
    "COIN",
    "ECON",
    "FED EX TK",
    "ELECTRIC",
    "2008",
    "TRL",
    "MC TRUCK",
    "UDT",
    "DESO",
    "UPS",
    "4S3BWAG62L30096",
    "SSSB",
    "LIA",
    "HTUN",
    "EZ DUMPER",
    "SUNA",
    "MALLARD",
    "ROCK",
    "TRASH TK",
    "AMERICAN",
    "VM",
    "19XFA1F58BE0143",
    "JRTR",
    "4BB5077",
    "DELFAST",
    "SCUR",
    "AUTC",
    "UD DS",
    "U HAUL",
    "COLE",
    "JMH",
    "UB",
    "MAIL TRUCK",
    "1N4BL4BV8KC1872",
    "KRAF",
    "1G8ZH5282VZ1642",
    "SPOR",
    "4T1BK46K17U0182",
    "BRI-MAR",
    "HMST",
    "5XYPKDA59LG6874",
    "PLDS",
    "JF1GG29624G8084",
    "ESCOTL",
    "LORI",
    "UNIT",
    "MATL",
    "PJ",
    "HERTZ",
    "2HGES26792H5467",
    "PJTM",
    "ICEB",
    "CUST",
    "CUT",
    "2T3P1RFV9LW1182",
    "EZDUMPER",
    "SCBFH7ZA7GC0570",
    "DLR",
    "3N1CB51D75L5139",
    "MAIL",
    "VALU",
    "KENMORE",
    "BASHAN",
    "TRLK",
    "PEQU",
    "ICEBEAR",
    "ARES",
    "BEND",
    "D & D",
    "JRRP",
    "JP",
    "S",
    "SGR",
    "2018",
    "US MAIL",
    "MCT",
    "MERC DODGE",
    "FTWD",
    "SCENIC VIEW",
    "LONGBO",
    "C",
    "1HD1KB4179Y6312",
    "PRIM",
    "SUN",
    "CARRYON",
    "BRTL",
    "TRAILOR",
    "ATM",
    "2T3F1RFVXLW1187",
    "HUCA",
    "US",
    "BRIMAR",
    "-",
    "CASI",
    "NARD",
    "GATO",
    "DANG FONG",
    "SW",
    "GILBERT",
    "DYKO",
    "DUSSELDORF",
    "2003",
    "MODEL",
    "KARA",
    "SPNR",
    "VENT",
    "MITCH",
    "6FAJ71",
    "1G2JB12F6471340",
    "POIS",
    "AMMO",
    "IKA",
    "NMERX",
    "HOLM",
    "2BD3611",
    "TUT",
    "HEEO",
    "BIG",
    "DEALER",
    "TURT",
    "COACHMEN",
    "JTDKN3DU6A01143",
    "CHICAGO",
    "TOW",
    "2013",
    "HT",
    "HTU",
    "HUMAN",
    "COLCO",
    "CARY",
    "NEO",
    "SOSGE",
    "SKYL",
    "GALV",
    "CROS",
    "GRECH",
    "MOBED",
    "WBAHJ6317PGD231",
    "BLK",
    "WHTNG",
    "GREAT DANE",
    "TOBR",
    "MT",
    "P4D",
    "LANK",
    "WK",
    "WABASH",
    "TRAILER",
    "JTDKT4K37B53306",
    "SUV",
    "TOPB",
    "LA JOLLA",
    "PREV",
    "WELL",
    "PAAM",
    "XB",
    "1FMEU15H9LLA053",
    "ORBEA",
    "BIKE FRIDAY",
    "MOTZ",
    "SCOTT",
    "3FA6P0G75ER3736",
    "TAM",
    "4T1BE32K95U0427",
    "5BL2341",
    "MUR",
    "2015",
    "TRAI",
    "VAN",
    "TEXA",
    "NAVI",
    "BIKTRIS",
    "ICU",
    "1FTFW1RG6LFB842",
    "3VW4T7AU1GM0162",
    "CARG",
    "SALCJ2FX7LH8453",
    "NNT",
    "3N1AB7AP7JL6406",
    "9DP1693",
    "JTMRFREV2JD2350",
    "WINNA",
    "1FMCU0G70GUB534",
    "180",
    "JM3KE4CY2G06876",
    "JTMA1RFV3KJ0132",
    "1N4AL3AP3FC5890",
    "5NPD84LF6HH0198",
    "MIZZ",
    "SHSRD78555U3365",
    "1D7HA18N56J1034",
    "5YMKT6C31H0U395",
    "YUK",
    "4CD1022",
    "TRACTOR",
    "M",
    "JTMRWRFV1LD0704",
    "1VWBN7A37DC0970",
    "JH4CU26609C0350",
    "1HGFA16516L0589",
    "5NPD84LF9HH0607",
    "3N1CE2CP0JL3564",
    "AGA",
    "1FTVX12596NB720",
    "2T1BU4EE3CC8369",
    "ABY",
    "CHONGQING",
    "2BZ4372",
    "MSP",
    "MITZL",
    "ALABAMA",
    "4T1BF22K3YU1039",
    "AMTI",
    "TECTRON",
    "CLUB CAR",
    "RALLY",
    "NUWA",
    "VWMAZDA",
    "VNTO",
    "POINT",
    "EZGO",
    "RUKUS",
    "BRINKS",
    "ARI",
    "FISR",
    "MOTORCYCLE",
    "TOPT",
    "YONG",
    "TRAC",
    "NVAE",
    "HAULMARK",
    "CARRY-ON",
    "MTRA",
    "MTZR",
    "SANMAN COUNTY",
    "JIAJE",
    "ARII",
    "VENOM",
    "TAZHOU",
    "ZSTV",
    "ZNEL",
    "CAT",
    "TAZIHOU",
    "OLNEY",
    "CHMM",
    "SURETRAC",
    "UDUM",
    "SKAM",
    "ZHEJIANG SHANQI",
    "WINN",
    "TRUM",
    "SUNS",
    "ZOUZHILONG TECH",
    "ZHEJ",
    "EKO",
    "TAIZHOU ZHONG",
    "MAXX",
    "MARSHAL",
    "2020",
    "STAN",
    "FLYING WING",
    "BRRN",
    "COTTRELL",
    "JIANGSU",
    "CARMATE",
    "ALUM",
    "JUNG",
    "GIUP",
    "ZHEN",
    "ZHENG",
    "KUA",
    "SYMG",
    "ZERO",
    "FLYWHEEL",
    "CIMC",
]