mappings = {
    "HOND": "HONDA",
    "LINC": "LINCOLN",
    "MITS": "MITSUBISHI",
    "MAZD": "MAZDA",
    "LEXS": "LEXUS",
    "WSTR": None,
    "TSMR": None,
    "HYUN": "HYUNDAI",
    "SUBA": "SUBARU",
    "INFI": "INFINITI",
    "MERZ": "MERCEDES",
    "INFINITY": "INFINITI",
    "TOYTA": "TOYOTA",
    "CHEV": "CHEVROLET",
    "CHRY": "CHRYSLER",
    "CHRY \\": "CHRYSLER",
    "CHRYSLER\\": "CHRYSLER",
    "CHEVY": "CHEVROLET",
    "LANDROVER": "LAND ROVER",
    "TOYT": "TOYOTA",
    "DODG": "DODGE",
    "HAWK": None,
    "VOLV": "VOLVO",
    "NISS": "NISSAN",
    "CADI": "CADILLAC",
    "ACUR": "ACURA",
    "VOLKS": "VOLKSWAGEN",
    "MERCEDEZ": "MERCEDES",
    "INTERN": "INTERNATIONAL",
    "VOLK": "VOLKSWAGEN",
    "ACUA": "ACURA",
    "VW": "VOLKSWAGEN",
    "VOLKSWAGON": "VOLKSWAGEN",
    "TOYO": "TOYOTA",
    "FRHT": "FREIGHTLINER",
    "HYU": "HYUNDAI",
    "FLY WING": None,
    "HYUND": "HYUNDAI",
    "CADILAC": "CADILLAC",
    "MERCED": "MERCEDES",
    "MERC": "MERCEDES",
    "H0NDA": "HONDA",
    "SUBARY": "SUBARU",
    "FRT": "FREIGHTLINER",
    "TOY": "TOYOTA",
    "ISU": "ISUZU",
    "BUIC": "BUICK",
    "TOYOYA": "TOYOTA",
    "VOLSWAGEN": "VOLKSWAGEN",
    "HARLEY": "HARLEY-DAVIDSON",
    "TOYOA": "TOYOTA",
    "FORF": "FORD",
    "MITTSUBISHI": "MITSUBISHI",
    "TESL": "TESLA",
    "TOYOTAS": "TOYOTA",
    "TRANSPRO": None,
    "LEXU": "LEXUS",
    "LEXYS": "LEXUS",
    "MITZ": "MITSUBISHI",
    "SMRT": "SMART",
    "KIIA": "KIA",
    "TOYORTA": "TOYOTA",
    "PONT": "PONTIAC",
    "INTERNA": "INTERNATIONAL",
    "HUNDAI": "HYUNDAI",
    "KAUFMAN": None,
    "VOLSWAGON": "VOLKSWAGEN",
    "ALFA": "ALFA ROMEO",
    "MNNI": "MINI",
    "MERZCEDES BENZ": "MERCEDES-BENZ",
    "PORCHE": "PORSCHE",
    "HYND": "HYUNDAI",
    "GENISIS": "GENESIS",
    "LAND  ROVER": "LAND ROVER",
    "CHEVORLET": "CHEVROLET",
    "ZHEJIANG JIAJUE": None,
    "TAIZOU": None,
    "AUCRA": "ACURA",
    "INFIN": "INFINITI",
    "TOYORA": "TOYOTA",
    "GILG": None,
    "RAN": None,
    "FHTL": "FREIGHTLINER",
    "KW": "KENWORTH",
    "TTOYOTA": "TOYOTA",
    "ZR900": None,
    "SUZU": "SUZUKI",
    "VOLKSWGEN": "VOLKSWAGEN",
    "UT": None,
    "VOL": "VOLVO",
    "HINDA": "HYUNDAI",
    "CAMRY": "TOYOTA",
    "JAGU": "JAGUAR",
    "OTH": None,
    "FRIEHTLINER": "FREIGHTLINER",
    "BWS": "BMW",
    "NUSSAN": "NISSAN",
    "INFITI": "INFINITI",
    "JAG": "JAGUAR",
    "TRLR": None,
    "RIVIIAN": "RIVIAN",
    "LNDR": "LAND ROVER",
    "TUSLA": "TESLA",
    "TOYOTAL": "TOYOTA",
    "INTER": "INTERNATIONAL",
    "TAIZHOU": None,
    "SUNARU": "SUBARU",
    "ZHEJIANG": None,
    "ROVER": "LAND ROVER",
    "WEST": None,
    "HYN": "HYUNDAI",
    "NISSASNM": "NISSAN",
    "HYUNDAOI": "HYUNDAI",
    "TOYIOTA": "TOYOTA",
    "CHEVYT": "CHEVROLET",
    "PORS": "PORSCHE",
    "MAZ": "MAZDA",
    "LAN ROVER": "LAND ROVER",
    "CADDILAC": "CADILLAC",
    "SALVAGE": None,
    "MEREDES": "MERCEDES",
    "BUDDY": None,
    "JIAJUE": None,
    "4DNISSAN": "NISSAN",
    "LAMO": None,
    "NISSA": "NISSAN",
    "NISSAM": "NISSAN",
    "COTC": None,
    "SAT": "SATURN",
    "BMX": "BMW",
    "MOZDA": "MAZDA",
    "INT": "INTERNATIONAL",
    "PTRB": "PETERBILT",
    "MERCEDSES": "MERCEDES",
    "MASE": "MASERATI",
    "CRYSLER": "CHRYSLER",
    "CADIALLAC": "CADILLAC",
    "QUALITY": None,
    "UNKNOWN": None,
    "STRN": None,
    "SOLAR": None,
    "JANUS": None,
    "HODNA": "HONDA",
    "TOTOTA": "TOYOTA",
    "DATSON": "DATSUN",
    "PORSHE": "PORSCHE",
    "CHEVEROLET": "CHEVROLET",
    "HONDAS": "HONDA",
    "MINI COOPER": "MINI",
    "MAST": None,
    "RANGER ROVER": "RANGE ROVER",
    "CHAVY": "CHEVROLET",
    "PRIUS": "TOYOTA",
    "HITE": None,
    "HYUNDA": "HYUNDAI",
    "HYUNDI": "HYUNDAI",
    "NISSIAN": "NISSAN",
    "MERCEES": "MERCEDES",
    "HYUNAI": "HYUNDAI",
    "70WM": "BMW",
    "HUMM": "HUMMER",
    "ACRUA": "ACURA",
    "LEXIS": "LEXUS",
    "YONGFU": None,
    "BMW4": "BMW",
    "VOLKS WAGON": "VOLKSWAGEN",
    "TAIZHOU ZHONGEN": None,
    "QIAN": None,
    "CHYSLER": "CHRYSLER",
    "BENZ": "MERCEDES-BENZ",
    "SUBU": "SUBARU",
    "BWM": "BMW",
    "CHVY": "CHEVROLET",
    "INTL": "INTERNATIONAL",
    "HYUNDIA": "HYUNDAI",
    "THMS": None,
    "STLG": None,
    "KAWK": None,
    "CANAM": "CAN-AM",
    "TOTY": "TOYOTA",
    "JIAJU": None,
    "CHECY": "CHEVROLET",
    "JEEO": "JEEP",
    "TOYOYTA": "TOYOTA",
    "HD": "HARLEY-DAVIDSON",
    "MZDA": "MAZDA",
    "HYUNDRI": "HYUNDAI",
    "RANGE": "RANGE ROVER",
    "LINCON": "LINCOLN",
    "VOLKES": "VOLKSWAGEN",
    "MAZADA": "MAZDA",
    "CAD": "CADILLAC",
    "HOMESTEADER TRL": None,
    "CHYRSLER": "CHRYSLER",
    "DORD": "FORD",
    "SURE": None,
    "SUBRAU": "SUBARU",
    "VOLV0": "VOLVO",
    "SUBURU": "SUBARU",
    "HUYN": "HYUNDAI",
    "YOUNGFU": None,
    "STER": None,
    "MITSH": "MITSUBISHI",
    "TOYOTYA": "TOYOTA",
    "DOGDE": "DODGE",
    "ZHLONG": None,
    "TRANSPORT": None,
    "CADDILLAC": "CADILLAC",
    "NIS": "NISSAN",
    "CARRIE ON": None,
    "MECEDES": "MERCEDES",
    "PIAGGO": "PIAGGIO",
    "SUB": "SUBARU",
    "CHRYS": "CHRYSLER",
    "CHEVRLET": "CHEVROLET",
    "HYANDAI": "HYUNDAI",
    "MOPED": None,
    "MERCZ": "MERCEDES",
    "LEX": "LEXUS",
    "KENW": "KENWORTH",
    "MITUBISHI": "MITSUBISHI",
    "SUBRA": "SUBARU",
    "BUICK`": "BUICK",
    "SILVER": None,
    "POLESTAR": "POLESTAR",
    "LEGE": None,
    "CHRYSTLER": "CHRYSLER",
    "INFINTI": "INFINITI",
    "TAHOE": "CHEVROLET",
    "JIAJ": None,
    "CHEVERLOT": "CHEVROLET",
    "BISSAN": "NISSAN",
    "CHEY": "CHEVROLET",
    "ACCURA": "ACURA",
    "FOTD": "FORD",
    "OLDS": "OLDSMOBILE",
    "HUYNDAI": "HYUNDAI",
    "AMSTAR": None,
    "VOLKWAGON": "VOLKSWAGEN",
    "HYUDAI": "HYUNDAI",
    "PACE": None,
    "HUNDAY": "HYUNDAI",
    "TYOTA": "TOYOTA",
    "MITISUBISHI": "MITSUBISHI",
    "HYUNDDAI": "HYUNDAI",
    "HYUANDI": "HYUNDAI",
    "MITSUIBISHI": "MITSUBISHI",
    "CARRY ON T": None,
    "FOED": "FORD",
    "MIFU": None,
    "!2010HONDA": "HONDA",
    "AUDII": "AUDI",
    "VOLTSWAGON": "VOLKSWAGEN",
    "MIYTSUBISHI": "MITSUBISHI",
    "IZUZU": "ISUZU",
    "TOAT": "TOYOTA",
    "POLESTARE": "POLESTAR",
    "CHEBROLET": "CHEVROLET",
    "VOLLKSWAGEN": "VOLKSWAGEN",
    "CATTY": None,
    "MERCEDS": "MERCEDES",
    "SOLANA": None,
    "AN": None,
    "JEEG": "JEEP",
    "WV": "VOLKSWAGEN",
    "SENTRA": "NISSAN",
    "MERC EDEZ": "MERCEDES",
    "RIVA": None,
    "TOOYOTA": "TOYOTA",
    "HO0NDA": "HONDA",
    "SUZI": "SUZUKI",
    "PTBL": "PETERBILT",
    "CHEVROLETE": "CHEVROLET",
    "KEN": "KENWORTH",
    "ISUZ": "ISUZU",
    "YAMA": "YAMAHA",
    "GR": None,
    "VOLKSWAGAN": "VOLKSWAGEN",
    "LANDR": "LAND ROVER",
    "BENTLY": "BENTLEY",
    "PETE": "PETERBILT",
    "KAWKASKI": "KAWASAKI",
    "TOYTOA": "TOYOTA",
    "CHEVROLT": "CHEVROLET",
    "PACE SPORTS": None,
    "ITALIAN": None,
    "CHE": "CHEVROLET",
    "HON": "HONDA",
    "CHRSLER": "CHRYSLER",
    "LIN": "LINCOLN",
    "MIT": "MITSUBISHI",
    "VOLKWAGEN": "VOLKSWAGEN",
    "TOYOTTA": "TOYOTA",
    "MITSUBUSHI": "MITSUBISHI",
    "YIBEN": None,
    "USPS": None,
    "LAMBO": "LAMBORGHINI",
    "2023": None,
    "RDKG": None,
    "CHEVEROLT": "CHEVROLET",
    "LAMB": "LAMBORGHINI",
    "HYINDAI": "HYUNDAI",
    "MARSHALL": None,
    "SCIO": "SCION",
    "POR": "PORSCHE",
    "UTIL": None,
    "VOLVE": "VOLVO",
    "TOYOTOA": "TOYOTA",
    "TES": "TESLA",
    "AACURA": "ACURA",
    "F550": "FORD",
    "CADILLA": "CADILLAC",
    ";AND ROVER": "LAND ROVER",
    "TIYOTA": "TOYOTA",
    "SPRI": None,
    "WANC": None,
    "GENS": "GENESIS",
    "HOMDA": "HONDA",
    "BENT": "BENTLEY",
    "NAZD": "MAZDA",
    "2012": None,
    "STRG": None,
    "LEDXUS": "LEXUS",
    "DUCA": "DUCATI",
    "CFMO": "CFMOTO",
    "LNDROVER": "LAND ROVER",
    "SPAL": None,
    "BME": "BMW",
    "FHRT": "FREIGHTLINER",
    "ERZ": None,
    "PEACE SPORT": None,
    "LABD ROVER": "LAND ROVER",
    "EGIL": None,
    "ZHILONG": None,
    "GEN": "GENESIS",
    "KAWKASAKI": "KAWASAKI",
    "DOGE": "DODGE",
    "INFINTY": "INFINITI",
    "FROD": "FORD",
    "MIO 50": None,
    "TOYOITA 4": "TOYOTA",
    "TZTC": None,
    "ZHONGNENG": None,
    "MERCEDEZ BENZ": "MERCEDES-BENZ",
    "GRAY": None,
    "TOYT 2S": "TOYOTA",
    "ELANTRA": "HYUNDAI",
    "ROL": "ROLLS-ROYCE",
    "SCOOTER": None,
    "AALI": None,
    "APOL": None,
    "INTERNATINAL": "INTERNATIONAL",
    "POLS": "POLESTAR",
    "CHRSYLER": "CHRYSLER",
    "MITSIBUSI": "MITSUBISHI",
    "HYUNDAU": "HYUNDAI",
    "INFINI": "INFINITI",
    "VOLKSWAGEWN": "VOLKSWAGEN",
    "HYUNADI": "HYUNDAI",
    "MNI": "MINI",
    "HYUANDAI": "HYUNDAI",
    "PLYM": "PLYMOUTH",
    "CADILLIAC": "CADILLAC",
    "X-PRO": None,
    "MER": "MERCEDES",
    "FORD E 150": "FORD",
    "TELSA": "TESLA",
    "ASTRO": "CHEVROLET",
    "GLC300": "MERCEDES",
    "AUDU": "AUDI",
    "TAIZHOU ZHILONG": None,
    "TOWN & COUNTRY": "CHRYSLER",
    "TAIZHOU ZHONGNE": None,
    "CARR": None,
    "MITSO": "MITSUBISHI",
    "TOYPTA": "TOYOTA",
    "SANMEN": None,
    "ACURRA": "ACURA",
    "BU": "BUICK",
    "FREI": "FREIGHTLINER",
    "MAZERADI": "MASERATI",
    "CIVIC": "HONDA",
    "CHEVRLETE": "CHEVROLET",
    "SUBURA": "SUBARU",
    "MD": "MAZDA",
    "INGINITI": "INFINITI",
    "TOIYOTA": "TOYOTA",
    "MINNI": "MINI",
    "BAODIAO": None,
    "NISAN": "NISSAN",
    "HYNDI": "HYUNDAI",
    "HYINDA": "HYUNDAI",
    "HYUNDAIN": "HYUNDAI",
    "TOYYOTA": "TOYOTA",
    "ZNEN": None,
    "CANA": "CAN-AM",
    "DONG FANG": None,
    "MITSBUSHI": "MITSUBISHI",
    "PETERBUILT": "PETERBILT",
    "YUNDAI": "HYUNDAI",
    "GRAND": None,
    "GENU": "GENESIS",
    "HMDE": "HONDA",
    "NINGBO": None,
    "BRAN": None,
    "PTR": "PETERBILT",
    "TRANS PRO": None,
    "TAIZHOU QIANXIN": None,
    "H": None,
    "VANHOOL": "VAN HOOL",
    "DODGE RAM": "RAM",
    "2011": None,
    "MITSUBISH": "MITSUBISHI",
    "VOKSWAGON": "VOLKSWAGEN",
    "CHEVRELET": "CHEVROLET",
    "GATOR": None,
    "VOKS": "VOLKSWAGEN",
    "LAND ROVE": "LAND ROVER",
    "QIANXIN": None,
    "TOOYTA": "TOYOTA",
    "PETERBULT": "PETERBILT",
    "KRAFTSMAN": None,
    "LAND OVER": "LAND ROVER",
    "ITALICA": None,
    "UNKOWN": None,
    "BUIK": "BUICK",
    "CADILKAC": "CADILLAC",
    "ZHNG": None,
    "TAOI": "TOYOTA",
    "ZHIL": None,
    "ROLLS ROYCE": "ROLLS-ROYCE",
    "CHRYLSER": "CHRYSLER",
    "LAND ROV": "LAND ROVER",
    "FLYWING": None,
    "GONDA": "HONDA",
    "IZU": "ISUZU",
    "MCI": None,
    "TOYOTS": "TOYOTA",
    "TAIZ": None,
    "TAOTAO": "TAO TAO",
    "CHEVRO0LET": "CHEVROLET",
    "CLASH": None,
    "HYNDAI": "HYUNDAI",
    "BIGT": None,
    "SATU": "SATURN",
    "EPO": None,
    "TOYOT": "TOYOTA",
    "DUMP": None,
    "FRGHT": "FREIGHTLINER",
    "TOYOATA": "TOYOTA",
    "SATURRN": "SATURN",
    "2016": None,
    "9EC5338": None,
    "INFINITE": "INFINITI",
    "MITISHBSHI": "MITSUBISHI",
    "TAIWAN GOLDEN B": None,
    "VOLSKWAGON": "VOLKSWAGEN",
    "INF": "INFINITI",
    "PASSAT": "VOLKSWAGEN",
    "HUZH": None,
    "CHERVOLET": "CHEVROLET",
    "ALTIMA": "NISSAN",
    "HYUNDAY": "HYUNDAI",
    "EZDU": None,
    "HY": "HYUNDAI",
    "TOYTO": "TOYOTA",
    "CHEROLET": "CHEVROLET",
    "LINCLN": "LINCOLN",
    "HIUNDAI": "HYUNDAI",
    "PNT": "PONTIAC",
    "CADALLIC": "CADILLAC",
    "ETO": None,
    "MOTOR SCOOTER": None,
    "LUXUS": "LEXUS",
    "TOYOTA``": "TOYOTA",
    "SX4": "SUZUKI",
    "MAXDA": "MAZDA",
    "MERS": "MERCEDES",
    "SUZIUKI": "SUZUKI",
    "Z71": "CHEVROLET",
    "VOLKESWAGON": "VOLKSWAGEN",
    "MERCDES": "MERCEDES",
    "KAWSAKI": "KAWASAKI",
    "VOLKSWAGGON": "VOLKSWAGEN",
    "SURARU": "SUBARU",
    "GOLDEN BEE": None,
    "BRI MAR": None,
    "MITSU": "MITSUBISHI",
    "HYNDIA": "HYUNDAI",
    "CCHEVY": "CHEVROLET",
    "ROV": "LAND ROVER",
    "MUSTANG": "FORD",
    "TOYOVAL2012": "TOYOTA",
    "VOKSWAGEN": "VOLKSWAGEN",
    "FRGHTLNR": "FREIGHTLINER",
    "NISSASN": "NISSAN",
    "MITSUBISHUI": "MITSUBISHI",
    "SATR": "SATURN",
    "FORS": "FORD",
    "LEUS": "LEXUS",
    "DADGE": "DODGE",
    "HONDA`": "HONDA",
    "TOYATA": "TOYOTA",
    "YAMASAKI": "YAMAHA",
    "CHRYSLR": "CHRYSLER",
    "SUBUARU": "SUBARU",
    "HUNDYI": "HYUNDAI",
    "CHEVROLERT": "CHEVROLET",
    "MINI COOP": "MINI",
    "HIONDA": "HONDA",
    "YUKON": "GMC",
    "COGAR": "MERCURY",
    "MIS": "MITSUBISHI",
    "RANG": "RANGE ROVER",
    "MERCADEZ": "MERCEDES",
    "MADZ": "MAZDA",
    "GILL": None,
    "ACYUA": "ACURA",
    "VOLKWAG": "VOLKSWAGEN",
    "JEEF": "JEEP",
    "TYPHOON": "GMC",
    "NERCEDES": "MERCEDES",
    "SUSUKI": "SUZUKI",
    "COOPER": "MINI",
    "TPYOTA": "TOYOTA",
    "FTR": None,
    "HONA": "HONDA",
    "SEDAN": None,
    "ISZU": "ISUZU",
    "CHRYSLEER": "CHRYSLER",
    "PREM": None,
    "HNDA": "HONDA",
    "SUBURAU": "SUBARU",
    "TOYOTAA": "TOYOTA",
    "M34Z": "MAZDA",
    "MITSHUBISHI": "MITSUBISHI",
    "CEHV": "CHEVROLET",
    "KAW": "KAWASAKI",
    "SOLARA": "TOYOTA",
    "HUYAND": "HYUNDAI",
    "LEXUZ": "LEXUS",
    "NISSANM": "NISSAN",
    "TOYTQ": "TOYOTA",
    "LYNX": "MERCURY",
    "SUZ": "SUZUKI",
    "TOYOTAO": "TOYOTA",
    "NISS.": "NISSAN",
    "HYUDAO": "HYUNDAI",
    "1GCHG39U9312199": None,
    "BLUE": None,
    "ZUZUKI": "SUZUKI",
    "OLDMOBILE": "OLDSMOBILE",
    "MASERATTI": "MASERATI",
    "VOLKSWAGIN": "VOLKSWAGEN",
    "MERECEDES": "MERCEDES",
    "KENWO": "KENWORTH",
    "DIDGE": "DODGE",
    "INIFINITI": "INFINITI",
    "MERZEDES": "MERCEDES",
    "HYNDUAI": "HYUNDAI",
    "RANGEROVER": "RANGE ROVER",
    "OUTBACK": "SUBARU",
    "HOLNDA": "HONDA",
    "VOLKSWAGO": "VOLKSWAGEN",
    "VOKLS": "VOLKSWAGEN",
    "ACRUAA": "ACURA",
    "CHRYSL": "CHRYSLER",
    "WVOLKSWAGEN": "VOLKSWAGEN",
    "JANUAR": "JAGUAR",
    "HHOND": "HONDA",
    "CHRYSLAR": "CHRYSLER",
    "JETTA": "VOLKSWAGEN",
    "MERCEDEZ BNZ": "MERCEDES-BENZ",
    "BMI": "BMW",
    "TOYATO": "TOYOTA",
    "CHEVR": "CHEVROLET",
    "TOYOVAL2011": "TOYOTA",
    "MAZA": "MAZDA",
    "TOTO": "TOYOTA",
    "SICON": "SCION",
    "MITSUBSHI2DR": "MITSUBISHI",
    "ELGI": None,
    "HYUNDAIW": "HYUNDAI",
    "MADZA": "MAZDA",
    "CHEVEY": "CHEVROLET",
    "MITSIBUSHI": "MITSUBISHI",
    "FREIGHT LINER": "FREIGHTLINER",
    "TESCA": "TESLA",
    "SAA": "SAAB",
    "SCON": "SCION",
    "NISSAB": "NISSAN",
    "2T3ZFREV5FW2069": None,
    "MITSUBISIH": "MITSUBISHI",
    "BRMR": None,
    "CAI": None,
    "TOYTOTA": "TOYOTA",
    "NEW FLUER": None,
    "STATURN": "SATURN",
    "TOYOVAL2005": "TOYOTA",
    "SION": "SCION",
    "TOOTA": "TOYOTA",
    "TRANSIT": "FORD",
    "VOLTS": "CHEVROLET",
    "CHRYSER": "CHRYSLER",
    "VOLKVAL2014": "VOLKSWAGEN",
    "MISSAN": "NISSAN",
    "HUNYDA": "HYUNDAI",
    "1N4BA41E35C8089": None,
    "WOLSKWAGEN": "VOLKSWAGEN",
    "GRAND MARQUIS": "MERCURY",
    "MECURY": "MERCURY",
    "INFT": "INFINITI",
    "LINCOL": "LINCOLN",
    "HODA": "HONDA",
    "DOGGE": "DODGE",
    "KIAV": "KIA",
    "MERZ BENZ": "MERCEDES-BENZ",
    "HIA": "KIA",
    "VOLKSWAEN": "VOLKSWAGEN",
    "MITSUBICHI": "MITSUBISHI",
    "KEXUS": "LEXUS",
    "BMWVAL2009": "BMW",
    "BNW": "BMW",
    "CEHVROLET": "CHEVROLET",
    "ACCUR": "ACURA",
    "2007": None,
    "HYUNDE": "HYUNDAI",
    "MBW": "BMW",
    "HOME": None,
    "CRY": "CHRYSLER",
    "CHEVROLEY": "CHEVROLET",
    "RAV": "TOYOTA",
    "TYTA": "TOYOTA",
    "ORIO": None,
    "EXTREME": None,
    "GILLIG": "GILLIG",
    "NISSON": "NISSAN",
    "GIO": None,
    "NUS": None,
    "nan": None,
    "PORSCH": "PORSCHE",
    "LANR": "LAND ROVER",
    "AUGI": "AUDI",
    "RIYA": None,
    "RIDE ON": None,
    "PORSH": "PORSCHE",
    "LANROVER": "LAND ROVER",
    "4S": None,
    "HIND": "HYUNDAI",
    "TYOT": "TOYOTA",
    "MITISIBISHI": "MITSUBISHI",
    "HONDVAL1999": "HONDA",
    "HYUNDAI`": "HYUNDAI",
    "LOAD": None,
    "ISSU": "ISUZU",
    "HUYUNDAI": "HYUNDAI",
    "LEXSUS": "LEXUS",
    "TOTYA": "TOYOTA",
    "LEXIUS": "LEXUS",
    "SUBAR": "SUBARU",
    "DAEW": "DAEWOO",
    "FORSD": "FORD",
    "TOY0TA": "TOYOTA",
    "SMARVAL2010": "SMART",
    "TOYT (SCION)": "SCION",
    "MITZUBISHI": "MITSUBISHI",
    "INFINIT": "INFINITI",
    "JEEK": "JEEP",
    "VILKSWAGON": "VOLKSWAGEN",
    "QUANTUM": "VOLKSWAGEN",
    "6BR9831": None,
    "WOLKSWAGEN": "VOLKSWAGEN",
    "MITSUBSHI": "MITSUBISHI",
    "MIST": None,
    "RIDEON": None,
    "CHREYSLER": "CHRYSLER",
    "MERCEDE": "MERCEDES",
    "AUD": "AUDI",
    "SUZIKI": "SUZUKI",
    "CRNE": None,
    "MERCHURY": "MERCURY",
    "CHEVROLLET": "CHEVROLET",
    "LARO": None,
    "MBENZ": "MERCEDES-BENZ",
    "MITTS": "MITSUBISHI",
    "TOYOTA SCION": "SCION",
    "MAZDVAL2015": "MAZDA",
    "3FNY97": None,
    "KENIWORTH": "KENWORTH",
    "TOYOVAL2009": "TOYOTA",
    "MERCEDEZ-BENZ": "MERCEDES-BENZ",
    "CHR": "CHRYSLER",
    "NONE LISTED": None,
    "HONDVAL1994": "HONDA",
    "LICOLN": "LINCOLN",
    "SUBRARU": "SUBARU",
    "FOR": "FORD",
    "INFIT": "INFINITI",
    "FREIGHLINER": "FREIGHTLINER",
    "INFNIITI": "INFINITI",
    "INFINIFTY": "INFINITI",
    "PETER BUILT": "PETERBILT",
    "CHEVVAL2002": "CHEVROLET",
    "VESP": "VESPA",
    "HYUNUNDAI": "HYUNDAI",
    "BUICL": "BUICK",
    "FORDD": "FORD",
    "RANGE ROV": "RANGE ROVER",
    "GRUMAN": "GRUMMAN",
    "MERCEDEA": "MERCEDES",
    "COPPER": None,
    "CHEVROLOET": "CHEVROLET",
    "VOLS": "VOLVO",
    "MITIBISHI": "MITSUBISHI",
    "NISSIN": "NISSAN",
    "LEUX": "LEXUS",
    "CHEVOLETE": "CHEVROLET",
    "BIG HORN": "RAM",
    "FIRD": "FORD",
    "SUBARA": "SUBARU",
    "LEXUUS": "LEXUS",
    "FREIGHTLINE": "FREIGHTLINER",
    "CAMA": None,
    "TOYOVAL2014": "TOYOTA",
    "HYUNVAL2000": "HYUNDAI",
    "NISAAN": "NISSAN",
    "TOTOYA": "TOYOTA",
    "KI": "KIA",
    "COLEMAN": None,
    "CHRISLER": "CHRYSLER",
    "ACURVAL2004": "ACURA",
    "UD": None,
    "BRMA": None,
    "MITI": "MITSUBISHI",
    "COROLLA": "TOYOTA",
    "T0YT": "TOYOTA",
    "VOLK WAG": "VOLKSWAGEN",
    "NIMR": None,
    "TOMAS": "THOMAS",
    "THOM": "THOMAS",
    "MEBE": None,
    "RANG ROVER": "RANGE ROVER",
    "MAZDVAL2004": "MAZDA",
    "EXUS": "LEXUS",
    "CEV": "CHEVROLET",
    "BUCK": "BUICK",
    "AUDO": "AUDI",
    "KAWASAWKI": "KAWASAKI",
    "MASARATI": "MASERATI",
    "SUZUKKI": "SUZUKI",
    "RAV4": "TOYOTA",
    "HOBDA": "HONDA",
    "OLD MOBILE": "OLDSMOBILE",
    "MOTOBRAVO": None,
    "CHEVROELT": "CHEVROLET",
    "BMW`": "BMW",
    "HUYNDA": "HYUNDAI",
    "DASH": None,
    "2AC9011": None,
    "SABB": "SAAB",
    "MITXS": "MITSUBISHI",
    "CHYRSTLER": "CHRYSLER",
    "SSR": "CHEVROLET",
    "TOYOTA CAMRY": "TOYOTA",
    "KING RING": None,
    "HONDVAL2005": "HONDA",
    "MADA": "MAZDA",
    "HYANDI": "HYUNDAI",
    "ACUFRA": "ACURA",
    "ESCO": None,
    "EADU": None,
    "CHEVE": "CHEVROLET",
    "CAPRICE": "CHEVROLET",
    "MITSUBISUI": "MITSUBISHI",
    "MAXIMA": "NISSAN",
    "VOK": "VOLKSWAGEN",
    "CHECVY": "CHEVROLET",
    "CHEVVAL2007": "CHEVROLET",
    "LEXI": "LEXUS",
    "RANGROVER": "RANGE ROVER",
    "PONIAC": "PONTIAC",
    "MITZIBUSHI": "MITSUBISHI",
    "KIW": None,
    "SAB": "SAAB",
    "DDOGE": "DODGE",
    "YOYOTA": "TOYOTA",
    "POMT": "PONTIAC",
    "E350": "FORD",
    "SHANGHAI": None,
    "MITZU": "MITSUBISHI",
    "TOYP": "TOYOTA",
    "MITSUBIHI": "MITSUBISHI",
    "1J4GR48K46C1478": None,
    "TOYT 4S": "TOYOTA",
    "MERDZ": "MERCEDES",
    "MASERSTI": "MASERATI",
    "MC": None,
    "KIA SOUL": "KIA",
    "CHY": "CHRYSLER",
    "CADDI": "CADILLAC",
    "CHEEVROLET": "CHEVROLET",
    "SATERN": "SATURN",
    "INFNITY": "INFINITI",
    "UHAUL": None,
    "SOUT": None,
    "PREMIER": None,
    "FANGYUE": None,
    "CHEVRLOTE": "CHEVROLET",
    "BUEL": "BUELL",
    "CHEVYROLET": "CHEVROLET",
    "FREIGHT": "FREIGHTLINER",
    "MISTUBISHI": "MITSUBISHI",
    "MERCCURY": "MERCURY",
    "HONAD": "HONDA",
    "MISSIBISHI": "MITSUBISHI",
    "CHRYSTER": "CHRYSLER",
    "AUSTIN MARTIN": "ASTON MARTIN",
    "CHEVROLE": "CHEVROLET",
    "PIER SPEED": None,
    "JIFF": None,
    "MEERCEDES": "MERCEDES",
    "ELDO": "CADILLAC",
    "HOMEMADE": None,
    "GLAV": None,
    ";NISSAN": "NISSAN",
    "MAVDA": "MAZDA",
    "IFINITI": "INFINITI",
    "LEONARD": None,
    "DONGFANG": None,
    "BASH": None,
    "CRYSTLER": "CHRYSLER",
    "IA": None,
    "DODGVAL2006": "DODGE",
    "FORD`": "FORD",
    "CROWN": "TOYOTA",
    "HUYDIA": "HYUNDAI",
    "CAM": None,
    "CHHRYSLER": "CHRYSLER",
    "BMWVAL2015": "BMW",
    "JA32W8FV1DU0176": None,
    "MALIBU": "CHEVROLET",
    "CHVROLET": "CHEVROLET",
    "INFINITII": "INFINITI",
    "E-TON BEAMER": None,
    "PERO": None,
    "4D": None,
    "M BENZ": "MERCEDES-BENZ",
    "TOYOVA": "TOYOTA",
    "CARRY": None,
    "GORRILLA": None,
    "VO;KS": "VOLKSWAGEN",
    "LINCOLIN": "LINCOLN",
    "MURCURY": "MERCURY",
    "ACURU": "ACURA",
    "LAND": "LAND ROVER",
    "INIFNITY": "INFINITI",
    "DUKATI": "DUCATI",
    "NISIAN": "NISSAN",
    "PILOT": "HONDA",
    "TOYOVAL2007": "TOYOTA",
    "FORDVAL2004": "FORD",
    "APOLLO": None,
    "PONTIC": "PONTIAC",
    "CHRYVAL2007": "CHRYSLER",
    "TOT": "TOYOTA",
    "TOYOTSA": "TOYOTA",
    "T0YOTA": "TOYOTA",
    "MISTH": "MITSUBISHI",
    "CHYST": "CHRYSLER",
    "KNAFU6A29B54609": None,
    "HONDAD": "HONDA",
    "DOSGE": "DODGE",
    "WORK": None,
    "LEXUS350": "LEXUS",
    "TOYOVAL2010": "TOYOTA",
    "MERVEDES": "MERCEDES",
    "THOM BUS": "THOMAS",
    "TMSR": None,
    "FORD VAN": "FORD",
    "INIFINITY": "INFINITI",
    "JONWAY": None,
    "HYTR": None,
    "ERL": None,
    "XINGYUE": None,
    "SCIONQ": "SCION",
    "FOD": "FORD",
    "CHEVY GEO": "GEO",
    "HANDA": "HONDA",
    "EAGL": "EAGLE",
    "SUBURBAN": "CHEVROLET",
    "VOLKSWAGEB": "VOLKSWAGEN",
    "NISSAN SENTRA": "NISSAN",
    "KAWASKI": "KAWASAKI",
    "MERCEDESBENZ": "MERCEDES-BENZ",
    "CHV": "CHEVROLET",
    "UTILITY": None,
    "INFN": "INFINITI",
    "ORD": "FORD",
    "CADALLAC": "CADILLAC",
    "LEXUX": "LEXUS",
    "MERTZ": "MERCEDES",
    "MISTI": "MITSUBISHI",
    "MERRZ": "MERCEDES",
    "METROPOLITAN": None,
    "JAUAR": "JAGUAR",
    "INTE": "INTERNATIONAL",
    "MISUBISHI": "MITSUBISHI",
    "NISSN": "NISSAN",
    "CAMERY": "TOYOTA",
    "ROAD": None,
    "MISTSUBISHI": "MITSUBISHI",
    "STAR": None,
    "SHORELANDER": None,
    "VLKSWAGON": "VOLKSWAGEN",
    "MEBZ": "MERCEDES",
    "MERC BENZ": "MERCEDES-BENZ",
    "HUYN 2D": "HYUNDAI",
    "INTEL": None,
    "CHYR": "CHRYSLER",
    "TOTT": "TOYOTA",
    "MERCEDED": "MERCEDES",
    "DDODGE": "DODGE",
    "PYLM": "PLYMOUTH",
    "NISN": "NISSAN",
    "GORD": "FORD",
    "FORK": "FORD",
    "HYUNDAIR": "HYUNDAI",
    "LOUTUS": "LOTUS",
    "MITSUBISIHI": "MITSUBISHI",
    "FLY SCOOTER": None,
    "PORSECHE": "PORSCHE",
    "MAZDZ": "MAZDA",
    "HOINDA": "HONDA",
    "LEXAS": "LEXUS",
    "SUSBARU": "SUBARU",
    "CHYS": "CHRYSLER",
    "MREZ": "MERCEDES",
    "EXPEDITION": "FORD",
    "PONIATIC": "PONTIAC",
    "CHARGER": "DODGE",
    "NT": None,
    "CHEVT": "CHEVROLET",
    "RANGE RVR": "RANGE ROVER",
    "CADILIAC": "CADILLAC",
    "HND": "HONDA",
    "TYN": None,
    "A": None,
    "SUBARUU": "SUBARU",
    "HONDVAL1996": "HONDA",
    "SUK": "SUZUKI",
    "MERCADE BENZ": "MERCEDES-BENZ",
    "DUCATO": "DUCATI",
    "VOLVVAL2007": "VOLVO",
    "HONDAY": "HONDA",
    "TOTYTA": "TOYOTA",
    "HENSIM": None,
    "DELRAY": None,
    "CEHVY": "CHEVROLET",
    "CEVEROLET": "CHEVROLET",
    "BWI": "BMW",
    "UNK": None,
    "MERCERY": "MERCURY",
    "CADALIC": "CADILLAC",
    "LEIKE": None,
    "MERQUIS": "MERCURY",
    "CHTYSLER": "CHRYSLER",
    "VOLKSWGON": "VOLKSWAGEN",
    "MONGOOSE": None,
    "FRT LINER": "FREIGHTLINER",
    "HOMD": "HONDA",
    "DONG": None,
    "EZLO": None,
    "YAHMAHA": "YAMAHA",
    "APPOLO": None,
    "TAGA": None,
    "HARL": "HARLEY-DAVIDSON",
    "TIYITA": "TOYOTA",
    "LEXUA": "LEXUS",
    "CHRSLYER": "CHRYSLER",
    "HONDVAL": "HONDA",
    "XFINITI": "INFINITI",
    "DYKON": None,
    "ORION": None,
    "MINICOOPER": "MINI",
    "ACRA": "ACURA",
    "VOLKSAGON": "VOLKSWAGEN",
    "HYUNA": "HYUNDAI",
    "MIITS": "MITSUBISHI",
    "NIAASAN": "NISSAN",
    "VK": "VOLKSWAGEN",
    "CHON": "HONDA",
    "ROD": None,
    "PONTAC": "PONTIAC",
    "JEEEP": "JEEP",
    "MB": "MERCEDES-BENZ",
    "MITSBISHI": "MITSUBISHI",
    "MITSSUBISHI": "MITSUBISHI",
    "SU BARU": "SUBARU",
    "PONIC": "PONTIAC",
    "INCOLN": "LINCOLN",
    "SUPERIOR": None,
    "VOVLO": "VOLVO",
    "OLDS MOBILE": "OLDSMOBILE",
    "FUJI": None,
    "TAIZHOU CHUANL": None,
    "PORSE": "PORSCHE",
    "MITSUB": "MITSUBISHI",
    "ACYRA": "ACURA",
    "ISSAN": "NISSAN",
    "NISSAAN": "NISSAN",
    "CHRYL": "CHRYSLER",
    "MITIS": "MITSUBISHI",
    "VOLKSWAGOON": "VOLKSWAGEN",
    "CARGO": None,
    "AURA": None,
    "VIP": None,
    "KYMC": "KYMCO",
    "TAOT": "TAO TAO",
    "TLOYOTA": "TOYOTA",
    "DODGEG": "DODGE",
    "GMX": None,
    "MERZ4S": "MERCEDES",
    "ODS": "OLDSMOBILE",
    "MERCADES": "MERCEDES",
    "QUALITY STEEL": None,
    "LAND EOVER": "LAND ROVER",
    "HONDVAL2000": "HONDA",
    "S550": "MERCEDES",
    "HYUNVAL2013": "HYUNDAI",
    "ATV": None,
    "AUTO": None,
    "KA": None,
    "JAQUAR": "JAGUAR",
    "TAUTAU": "TAO TAO",
    "SATRN": "SATURN",
    "FRE": "FREIGHTLINER",
    "36V663": None,
    "FELT": None,
    "SUBRUR": "SUBARU",
    "HUN": "HYUNDAI",
    "LINCLON": "LINCOLN",
    "XX": None,
    "EM": None,
    "HUYND": "HYUNDAI",
    "TOYOOTA": "TOYOTA",
    "TAIW": None,
    "MERS BENZ": "MERCEDES-BENZ",
    "HYUNI": "HYUNDAI",
    "FISK": "FISKER",
    "TOYOVAL2013": "TOYOTA",
    "PEDESTRIAN": None,
    "CHEVVAL2014": "CHEVROLET",
    "VOKWAGON": "VOLKSWAGEN",
    "FORD CAB": "FORD",
    "NISSAN FRONTEIR": "NISSAN",
    "JEVW": "JEEP",
    "MAZ4S": "MAZDA",
    "BAJA": None,
    "VANH": "VAN HOOL",
    "YAHAMA": "YAMAHA",
    "CRYS": "CHRYSLER",
    "STAR TRANS": None,
    "MRZ": "MERCEDES",
    "HONDVAL2010": "HONDA",
    "TAOTAN": "TAO TAO",
    "VOLKSWAGEM": "VOLKSWAGEN",
    "MERCEDS BENZ": "MERCEDES-BENZ",
    "JAOTAO": "TAO TAO",
    "PETER": "PETERBILT",
    "NIZZAN": "NISSAN",
    "YAM": "YAMAHA",
    "HONDDA": "HONDA",
    "FORDE": "FORD",
    "TAO TAO SCOOTER": "TAO TAO",
    "TOYOTA (SCION)": "SCION",
    "LESUS": "LEXUS",
    "NIISSAN": "NISSAN",
    "SURE-TRAC": None,
    "LINCONLN": "LINCOLN",
    "CHRYVAL2000": "CHRYSLER",
    "INFIVAL2010": "INFINITI",
    "BADO": None,
    "MERSEDES": "MERCEDES",
    "FERR": "FERRARI",
    "FPRD": "FORD",
    "HARLEYDAVIDSON": "HARLEY-DAVIDSON",
    "MIITSUBISHI": "MITSUBISHI",
    "JEEPVAL1998": "JEEP",
    "IZUSU": "ISUZU",
    "APRILLA": "APRILIA",
    "CDILLAC": "CADILLAC",
    "HONADA": "HONDA",
    "FORD E250": "FORD",
    "6BX9543": None,
    "DODGR": "DODGE",
    "MINNIAN": "MINI",
    "TLINER": "FREIGHTLINER",
    "HONS": "HONDA",
    "NISSVAL2014": "NISSAN",
    "CADLLAC": "CADILLAC",
    "KAWI": "KAWASAKI",
    "MERZ B": "MERCEDES-BENZ",
    "SUKI": "SUZUKI",
    "FORN": "FORD",
    "YOTOA": "TOYOTA",
    "MW": "BMW",
    "PRSCHE": "PORSCHE",
    "CHRUSLER": "CHRYSLER",
    "FRD": "FORD",
    "CHEV  PICKUP": "CHEVROLET",
    "FORD1": "FORD",
    "PONTICA": "PONTIAC",
    "SCID": "SCION",
    "SCI": "SCION",
    "TATT": None,
    "MITSHBISHI": "MITSUBISHI",
    "CHEV.": "CHEVROLET",
    "KAWASACKI": "KAWASAKI",
    "BOOM": None,
    "MERC BNZ": "MERCEDES-BENZ",
    "2010HONDA": "HONDA",
    "MITUSBISHI": "MITSUBISHI",
    "FORD T": "FORD",
    "FREIGHT VAN": "FREIGHTLINER",
    "MACDA": "MAZDA",
    "LINC TRUCK": "LINCOLN",
    "TACOMA": "TOYOTA",
    "MREC": "MERCEDES",
    "SUBUR": "SUBARU",
    "OLSMOBILE": "OLDSMOBILE",
    "MAZDVA": "MAZDA",
    "NISSAN QUEST": "NISSAN",
    "MERCQ": "MERCEDES",
    "TOYTS": "TOYOTA",
    "DHEVROLET": "CHEVROLET",
    "FLORIDA": None,
    "5NMS5CAAXLH2313": None,
    "VOV": "VOLVO",
    "HONIDA": "HONDA",
    "LEXCUS": "LEXUS",
    "MITSUBISSHI": "MITSUBISHI",
    "TEXTTRON": None,
    "NONE": None,
    "HYU N": "HYUNDAI",
    "CADILLACQ": "CADILLAC",
    "MIN": "MINI",
    "IHC": "INTERNATIONAL",
    "DAEWOOD": "DAEWOO",
    "ACCORD": "HONDA",
    "MASERITTI": "MASERATI",
    "HUY": "HYUNDAI",
    "SUNNY": "NISSAN",
    "NDMC": None,
    "MOTSUBISHI": "MITSUBISHI",
    "VILV": "VOLVO",
    "TOYIOOA": "TOYOTA",
    "MERCE": "MERCEDES",
    "CADIILLAC": "CADILLAC",
    "BLW": "BMW",
    "VPG": None,
    "YONFU": None,
    "INFININITI": "INFINITI",
    "KM": None,
    "HUDS": "HUDSON",
    "TAO": "TAO TAO",
    "CADILLAS": "CADILLAC",
    "CADILLIC": "CADILLAC",
    "VOVL": "VOLVO",
    "WRKH": None,
    "CHONGOING": None,
    "POBTIAC": "PONTIAC",
    "VULC": None,
    "2000": None,
    "LIEKE": None,
    "WHITE": None,
    "IZUZI": "ISUZU",
    "MERCIDEZ": "MERCEDES",
    "ZHEJIANG TAOTAO": None,
    "HUND": "HYUNDAI",
    "ZUMMERQ": None,
    "SABARU": "SUBARU",
    "NISSVAL1996": "NISSAN",
    "TOU": None,
    "MAKE": None,
    "2002": None,
    "PORCH": "PORSCHE",
    "XXXX": None,
    "FRIGHTLINER": "FREIGHTLINER",
    "NSSAN": "NISSAN",
    "UDI": "AUDI",
    "AOTAO": "TAO TAO",
    "HYDU": "HYUNDAI",
    "GMG": None,
    "RED": None,
    "FORD TK": "FORD",
    "SATURAN": "SATURN",
    "DUCOTI": "DUCATI",
    "TPYPTA": "TOYOTA",
    "GILL BU": "GILLIG",
    "HHONDA": "HONDA",
    "JEP": "JEEP",
    "2S": None,
    "HYUNDUI": "HYUNDAI",
    "OYOTA": "TOYOTA",
    "INIFITI": "INFINITI",
    "SPRINTER": "MERCEDES",
    "NOLKSWAGEN": "VOLKSWAGEN",
    "NISSSAN": "NISSAN",
    "SMART CAR": "SMART",
    "KAWAS": "KAWASAKI",
    "UU": None,
    "MITISHIBITSH": "MITSUBISHI",
    "MARCEDEZ": "MERCEDES",
    "2006": None,
    "FRIE": "FREIGHTLINER",
    "FEDEX": None,
    "VWOLKS": "VOLKSWAGEN",
    "FORD F150": "FORD",
    "BLACK": None,
    "MAROON": None,
    "T0Y0TA": "TOYOTA",
    "YAHAM": "YAMAHA",
    "OLDSMOBIL": "OLDSMOBILE",
    "TREX": None,
    "MERK": "MERCEDES",
    "ESCALADE": "CADILLAC",
    "ACU": "ACURA",
    "HONDAA": "HONDA",
    "NINSSAN": "NISSAN",
    "HMD": "HONDA",
    "TAYOTAYO": "TOYOTA",
    "REDLINE": None,
    "2HGFC2F76GH5421": None,
    "2014": None,
    "GENEVAL2003": "GENESIS",
    "PETERBELT": "PETERBILT",
    "HYUMDAI": "HYUNDAI",
    "VOLSK": "VOLKSWAGEN",
    "CHAN": None,
    "SATURNQ": "SATURN",
    "MRCEDES-BENZ": "MERCEDES-BENZ",
    "PORSCE": "PORSCHE",
    "WOLKSWAGON": "VOLKSWAGEN",
    "CHEVROET": "CHEVROLET",
    "LND RVR": "LAND ROVER",
    "SATUR": "SATURN",
    "MASDA": "MAZDA",
    "CJEVROLET": "CHEVROLET",
    "NEWFLYER": "NEW FLYER",
    "BARCH": None,
    "TYG": None,
    "DAKOTA": "DODGE",
    "BMWVAL2011": "BMW",
    "UD/ NISSAN": "NISSAN",
    "CHEVRELOET": "CHEVROLET",
    "FORDQ": "FORD",
    "HUINDAY": "HYUNDAI",
    "LE": None,
    "T6OYOTA": "TOYOTA",
    "RANGE OVER": "RANGE ROVER",
    "ODGE": "DODGE",
    "NISSA N": "NISSAN",
    "FREIGHTLINEER": "FREIGHTLINER",
    "HONDTK": "HONDA",
    "4X4": None,
    "HCRY": "CHRYSLER",
    "GRAND TENTON": None,
    "VILKW": "VOLKSWAGEN",
    "ISUZO": "ISUZU",
    "CHEVOLET": "CHEVROLET",
    "CHRYSLEY": "CHRYSLER",
    "MERCEDZ": "MERCEDES",
    "CHEVF": "CHEVROLET",
    "TOYOTO": "TOYOTA",
    "NISSNA": "NISSAN",
    "VOVLVO": "VOLVO",
    "FRIEGHTLINER": "FREIGHTLINER",
    "ASTO": "ASTON MARTIN",
    "ISUSU": "ISUZU",
    "NISSVAL2010": "NISSAN",
    "HONDVAL2007": "HONDA",
    "VOLKW": "VOLKSWAGEN",
    "PONITAC": "PONTIAC",
    "SSAB": "SAAB",
    "LLV": None,
    "COAC": "COACH",
    "VOLKSWAGN": "VOLKSWAGEN",
    "JEET": "JEEP",
    "JEFF": None,
    "HIUNDAY": "HYUNDAI",
    "NOSSAN": "NISSAN",
    "PRO STAR": "INTERNATIONAL",
    "CVEHROLET": "CHEVROLET",
    "TOYOTA VAN": "TOYOTA",
    "TOYO SCION": "SCION",
    "NISSVAL2011": "NISSAN",
    "OND": "HONDA",
    "CHEVYCOL": "CHEVROLET",
    "SUBAA": "SUBARU",
    "INFITITI": "INFINITI",
    "GHOST": "ROLLS-ROYCE",
    "BMA": "BMW",
    "NISSAS": "NISSAN",
    "LEXUES": "LEXUS",
    "VOLKSWA": "VOLKSWAGEN",
    "MAZD SW": "MAZDA",
    "SI": None,
    "UD NISSAN": "NISSAN",
    "CHEV I": "CHEVROLET",
    "OYT": "TOYOTA",
    "KAWA": "KAWASAKI",
    "SATUTN": "SATURN",
    "MAS": "MASERATI",
    "CALI": None,
    "NISSVAL2003": "NISSAN",
    "LEIK": None,
    "DODGECHEVY": None,
    "POINTIAC": "PONTIAC",
    "MITSIBISHI": "MITSUBISHI",
    "USUZU": "ISUZU",
    "VOL VO": "VOLVO",
    "Q5": "AUDI",
    "DF4958": None,
    "MER BENZ": "MERCEDES-BENZ",
    "SHUTTLE BUS": None,
    "PLYMOTH": "PLYMOUTH",
    "AUID": "AUDI",
    "MOTORELI": None,
    "PORSC": "PORSCHE",
    "HARLEY DAVID": "HARLEY-DAVIDSON",
    "TOYOTAT": "TOYOTA",
    "WORT": None,
    "HUYANDI": "HYUNDAI",
    "DCION": "SCION",
    "INIFI": "INFINITI",
    "MITSUSHI": "MITSUBISHI",
    "INFIVAL2013": "INFINITI",
    "CHRVROLET": "CHEVROLET",
    "NISSANA": "NISSAN",
    "MOTRA": None,
    "MERURY": "MERCURY",
    "AUDIVAL2008": "AUDI",
    "MERZS": "MERCEDES",
    "TIYOT": "TOYOTA",
    "SUPERHORNET": None,
    "HYAN": "HYUNDAI",
    "HUMAN BEING": None,
    "JAGR": "JAGUAR",
    "AMERICANA": None,
    "MERCVAL2007": "MERCEDES",
    "ACUTA": "ACURA",
    "PEACE SPORTS": None,
    "MERCEDEZ BENS": "MERCEDES-BENZ",
    "INTINITI": "INFINITI",
    "INVINITI": "INFINITI",
    "MOTIVE": None,
    "TOA TOA": "TAO TAO",
    "VOLO": "VOLVO",
    "NINMBO": None,
    "INTL TRUCK": "INTERNATIONAL",
    "CHEVROLTT": "CHEVROLET",
    "TOTYOTA": "TOYOTA",
    "HONDAI": "HONDA",
    "HONDQ": "HONDA",
    "VOLKS WAG": "VOLKSWAGEN",
    "ONEA": None,
    "VLOK": "VOLKSWAGEN",
    "WEST TK": "WESTERN STAR",
    "TCS DYKON": None,
    "VOLKS WAGEN": "VOLKSWAGEN",
    "FRIGHT": "FREIGHTLINER",
    "DENALI": "GMC",
    "GOLD": None,
    "MITISHIBI": "MITSUBISHI",
    "CHEVY VAN": "CHEVROLET",
    "INFINITYQ": "INFINITI",
    "TOYT4DR": "TOYOTA",
    "CCC": None,
    "DATS": "DATSUN",
    "GREEN POWER": None,
    "KENILWORTH": "KENWORTH",
    "ALFA ROMERO": "ALFA ROMEO",
    "VOLVO TK": "VOLVO",
    "JJEEP": "JEEP",
    "2010": None,
    "HYUB=NDAI": "HYUNDAI",
    "MECEDEZ": "MERCEDES",
    "BINTILLI": "BINTELLI",
    "VOLKAWAGEN": "VOLKSWAGEN",
    "MITSUBISHI N-24": "MITSUBISHI",
    "HONDY": "HONDA",
    "LRXUS": "LEXUS",
    "4DR": None,
    "MERCEDEZ BEN": "MERCEDES-BENZ",
    "SNOW BEAR": None,
    "NISANO": "NISSAN",
    "SUBERU": "SUBARU",
    "CHEVVAL2013": "CHEVROLET",
    "TOTOT": "TOYOTA",
    "TK": None,
    "HMC": None,
    "HYUDAY": "HYUNDAI",
    "VOLKVAL2012": "VOLKSWAGEN",
    "VOLVO 4DR": "VOLVO",
    "INTERNATI": "INTERNATIONAL",
    "H0ND": "HONDA",
    "TIYT": "TOYOTA",
    "CHRYLER": "CHRYSLER",
    "MEZ": "MERCEDES",
    "MERZEDS": "MERCEDES",
    "FTL": "FREIGHTLINER",
    "NP": None,
    "SAZUKI": "SUZUKI",
    "SATURB": "SATURN",
    "COOP": "MINI",
    "GOSH": None,
    "CHRYSLET": "CHRYSLER",
    "TOYOTA PRIUS": "TOYOTA",
    "CRANE CARRIER": None,
    "CANONDALE": "CANNONDALE",
    "RANGE ROVR": "RANGE ROVER",
    "MERCVAL2013": "MERCEDES",
    "TIGUAN": "VOLKSWAGEN",
    "DOSG": "DODGE",
    "MITSUBISHU": "MITSUBISHI",
    "LANCASTER": None,
    "GENEVAL2002": "GENESIS",
    "MRCEDES": "MERCEDES",
    "VACR": None,
    "CHEVU": "CHEVROLET",
    "CHRYSLEWR": "CHRYSLER",
    "INT'L": "INTERNATIONAL",
    "VOLTSWAGEN": "VOLKSWAGEN",
    "FORDVAL2002": "FORD",
    "CHEVROLEGT": "CHEVROLET",
    "MERBENZ": "MERCEDES-BENZ",
    "LANCE": None,
    "INFIITIT": "INFINITI",
    "DOD": "DODGE",
    "HUMAN-BEING": None,
    "PONTIAV": "PONTIAC",
    "AUCI": "AUDI",
    "AVURA": "ACURA",
    "HEIL": None,
    "HONDVA": "HONDA",
    "VOLKSWAGE": "VOLKSWAGEN",
    "MITSUUBISHI": "MITSUBISHI",
    "ACAD": None,
    "CHEC": "CHEVROLET",
    "ACUARA": "ACURA",
    "ARUCA": "ACURA",
    "LANDDROVER": "LAND ROVER",
    "FORDCN": "FORD",
    "UNITED STATES": None,
    "INFIVA": "INFINITI",
    "TOYOT TK": "TOYOTA",
    "CHYL": "CHRYSLER",
    "MRCEDEZ": "MERCEDES",
    "NISSAN / UD": "NISSAN",
    "CRRY": None,
    "FREIGHT LNR": "FREIGHTLINER",
    "PETERBUITL": "PETERBILT",
    "HONDA2DR": "HONDA",
    "NISS4": "NISSAN",
    "VIAGGIO": "PIAGGIO",
    "MAD": "MAZDA",
    "LEXUS4DR": "LEXUS",
    "TAO TAO 50": "TAO TAO",
    "HONDAQ": "HONDA",
    "CARRY ON": None,
    "LODA": None,
    "VOLKSAGEN": "VOLKSWAGEN",
    "BECK": None,
    "MISS": "MITSUBISHI",
    "MERZB": "MERCEDES",
    "HAELEY": "HARLEY-DAVIDSON",
    "NC": None,
    "INIF": "INFINITI",
    "PIAG": "PIAGGIO",
    "CRAN": None,
    "SUPER HORNET": None,
    "SUBAUR": "SUBARU",
    "CHRIS": "CHRYSLER",
    "FREIGHTLNR": "FREIGHTLINER",
    "BOX": None,
    "ZHEJIANG JONWAY": None,
    "VNFORD": "FORD",
    "SUZIK": "SUZUKI",
    "INTERNATION": "INTERNATIONAL",
    "CEHVORLET": "CHEVROLET",
    "MERCURI": "MERCURY",
    "PORC": "PORSCHE",
    "KENWOOD": None,
    "LAND RVER": "LAND ROVER",
    "VOLKSWAG": "VOLKSWAGEN",
    "HUANDAI": "HYUNDAI",
    "MCLA": "MCLAREN",
    "SATURNE": "SATURN",
    "SKY INC": None,
    "CADY": "CADILLAC",
    "BRECHBILL": None,
    "EPD": None,
    "MITSUBIHSHI": "MITSUBISHI",
    "PT": None,
    "T0Y0T": "TOYOTA",
    "INTN": "INTERNATIONAL",
    "CHRISTLER": "CHRYSLER",
    "BUW": "BMW",
    "FLASH": None,
    "BUICJ": "BUICK",
    "CHRYSELR": "CHRYSLER",
    "TOYOAT": "TOYOTA",
    "VLKS": "VOLKSWAGEN",
    "ALPHA": "ALFA ROMEO",
    "SCIONIA": "SCION",
    "MERCEDEZ B": "MERCEDES-BENZ",
    "HERCHEE": None,
    "BART": None,
    "FORE": "FORD",
    "TOYUOTA": "TOYOTA",
    "XIAMEN XIASHING": None,
    "DOFGE": "DODGE",
    "TOYOVAL2001": "TOYOTA",
    "KEXU": "LEXUS",
    "KINC": None,
    "FABRIQUE": None,
    "ISZUZU": "ISUZU",
    "SE": None,
    "F0RD": "FORD",
    "TOYOY": "TOYOTA",
    "TRITON": "MITSUBISHI",
    "CHVEY": "CHEVROLET",
    "MERCDZ": "MERCEDES",
    "BELM": None,
    "CHEBY": "CHEVROLET",
    "MININ": "MINI",
    "PONTIA": "PONTIAC",
    "CHEVOROLET": "CHEVROLET",
    "RUC": None,
    "HAUL": None,
    "CHWVY": "CHEVROLET",
    "LANDROV": "LAND ROVER",
    "SBARU": "SUBARU",
    "TOUOTA": "TOYOTA",
    "VALKS": "VOLKSWAGEN",
    "VOLKSW": "VOLKSWAGEN",
    "MINO": "MINI",
    "SUBR": "SUBARU",
    "BUS": None,
    "BIG TEX": None,
    "CRISWELL": None,
    "TAOTO": "TAO TAO",
    "HYNDAY": "HYUNDAI",
    "QIPAI": None,
    "ACUIRA": "ACURA",
    "HYUDNAI": "HYUNDAI",
    "LMAND ROVER": "LAND ROVER",
    "MERZD": "MERCEDES",
    "MITSUBISHIE": "MITSUBISHI",
    "STELLA": None,
    "CAILLAC": "CADILLAC",
    "SUBARULEGACY": "SUBARU",
    "CHVE": "CHEVROLET",
    "FRG": "FREIGHTLINER",
    "PERS": None,
    "CHEVTOLET": "CHEVROLET",
    "BUI CK": "BUICK",
    "MOTOR": None,
    "LNDRVR": "LAND ROVER",
    "INFINITT": "INFINITI",
    "CHEVROOET": "CHEVROLET",
    "FREIGTLINER": "FREIGHTLINER",
    "FORD F450": "FORD",
    "GMC S": "GMC",
    "MINIVAL2013": "MINI",
    "TOYR": "TOYOTA",
    "VOLKXS": "VOLKSWAGEN",
    "CHE VY": "CHEVROLET",
    "]LEXUS": "LEXUS",
    "CADILLACE": "CADILLAC",
    "PENSKE": None,
    "QIYE": None,
    "LND ROV": "LAND ROVER",
    "FREIGHTL": "FREIGHTLINER",
    "MERCUR": "MERCURY",
    "INTERNATIONA": "INTERNATIONAL",
    "HEV": "CHEVROLET",
    "HOMESTEADER": None,
    "CHVYE": "CHEVROLET",
    "STERL": "STERLING",
    "LAND ROVWR": "LAND ROVER",
    "MITISBISHI": "MITSUBISHI",
    "FORM": "FORD",
    "PROS": None,
    "MINIVAL2006": "MINI",
    "MNI COOPER": "MINI",
    "LAND RVR": "LAND ROVER",
    "BGTX": None,
    "HPNDA": "HONDA",
    "2004": None,
    "MERCVAL2006": "MERCEDES",
    "ZHILONG TECH": None,
    "FREITHLINER": "FREIGHTLINER",
    "KAIT": None,
    "CHECOROLET": "CHEVROLET",
    "GT": None,
    "INFIINIIT": "INFINITI",
    "INFI NTI": "INFINITI",
    "CHERVROLET": "CHEVROLET",
    "TOTOYTA": "TOYOTA",
    "NISSANS": "NISSAN",
    "CHEVY0": "CHEVROLET",
    "PCH": "PORSCHE",
    "FORC": "FORD",
    "HEVY": "CHEVROLET",
    "MECEDES BENZ": "MERCEDES-BENZ",
    "INIFINIT": "INFINITI",
    "FREIGHT HAULER": None,
    "E320": "MERCEDES",
    "OTHR": None,
    "JAQ": "JAGUAR",
    "HONDSA": "HONDA",
    "LEXUS`": "LEXUS",
    "MASERAII": "MASERATI",
    "GMS": "GMC",
    "SIERRA": "GMC",
    "JH4DB7656WS0073": None,
    "IC": None,
    "SUBARAU": "SUBARU",
    "MRZD": "MERCEDES",
    "MERCUCY": "MERCURY",
    "VOLKSWAGPN": "VOLKSWAGEN",
    "HIN": "HYUNDAI",
    "2DR": None,
    "YOYT": "TOYOTA",
    "PORSCGE": "PORSCHE",
    "CUEVY": "CHEVROLET",
    "LEXUVAL2003": "LEXUS",
    "CHEVRPLET": "CHEVROLET",
    "MADD": "MAZDA",
    "QUALITY TRAILER": None,
    "ACURVAL2003": "ACURA",
    "LANDCRUISER": "TOYOTA",
    "MITT": "MITSUBISHI",
    "FRTL": "FREIGHTLINER",
    "HHYUNDAI": "HYUNDAI",
    "ACURVAL2010": "ACURA",
    "RAMCV": "RAM",
    "MARC": "MERCURY",
    "GMC TK": "GMC",
    "HOMS": "HONDA",
    "RIALTA": "VOLKSWAGEN",
    "AMER": None,
    "GMA": "GMC",
    "VPG/U NAME IT": None,
    "SUBERO": "SUBARU",
    "CIDI": "CADILLAC",
    "KIS": "KIA",
    "LEXXUS": "LEXUS",
    "JEES": "JEEP",
    "HYHUNDAI": "HYUNDAI",
    "CHEVROLETTE": "CHEVROLET",
    "INAT": "INTERNATIONAL",
    "INTR": "INTERNATIONAL",
    "TOYOUA": "TOYOTA",
    "SHOR": None,
    "VOLKSWAEGN": "VOLKSWAGEN",
    "BUICK TK": "BUICK",
    "VOLK SWAGON": "VOLKSWAGEN",
    "MGS": "MG",
    "VOLSKS": "VOLKSWAGEN",
    "FATBEAR": "HARLEY-DAVIDSON",
    "TARTER": None,
    "HARLEY D": "HARLEY-DAVIDSON",
    "GMD": "GMC",
    "JMST": None,
    "INI": "INFINITI",
    "CVEV": "CHEVROLET",
    "HOME STAR": None,
    "PETERB": "PETERBILT",
    "HODD": "HONDA",
    "JAMIS": None,
    "SUTURN": "SATURN",
    "KAUF": None,
    "SHEV": "CHEVROLET",
    "NSS": "NISSAN",
    "TOMO": None,
    "IFINITY": "INFINITI",
    "HYANDAU": "HYUNDAI",
    "LIINCOLN": "LINCOLN",
    "MDX": "ACURA",
    "ACURAMDX": "ACURA",
    "CHRVY": "CHEVROLET",
    "TBU": None,
    "VANDERHALL": "VANDERHALL",
    "PITERBUILT": "PETERBILT",
    "FACE": None,
    "MINIBIKE": None,
    "UBARU": "SUBARU",
    "1FADP3F2XDL1682": None,
    "CEVROLET": "CHEVROLET",
    "MITSUBASHI": "MITSUBISHI",
    "SUBARUSW": "SUBARU",
    "SUB4DR": "SUBARU",
    "RAINGE ROVER": "RANGE ROVER",
    "SPEED": None,
    "1HGCR2F16HA2204": None,
    "SLIN": None,
    "WDBUF76J25A6414": None,
    "PONTI": "PONTIAC",
    "MAZS": "MAZDA",
    "HOD": "HONDA",
    "MINI-COOPER": "MINI",
    "3": None,
    "SUBAVAL2014": "SUBARU",
    "ACURS": "ACURA",
    "HONDA4": "HONDA",
    "KEMP": None,
    "INTL DS": "INTERNATIONAL",
    "KEEP": None,
    "FCA": None,
    "HYUND1": "HYUNDAI",
    "KALW": None,
    "CRCA": None,
    "HOONDA": "HONDA",
    "ACURVAL2005": "ACURA",
    "HONDA TRUCK": "HONDA",
    "VOVO": "VOLVO",
    "GILIG": "GILLIG",
    "TOYOTA`": "TOYOTA",
    "LONCOLN": "LINCOLN",
    "AUTOCAR": "AUTOCAR",
    "TRIU": "TRIUMPH",
    "LINCOLB": "LINCOLN",
    "SUBS": "SUBARU",
    "V": None,
    "RANGE R": "RANGE ROVER",
    "AMO": None,
    "PORCSHE": "PORSCHE",
    "JEEPVAL2014": "JEEP",
    "HYDAI": "HYUNDAI",
    "`TOYOTA": "TOYOTA",
    "WHIT": None,
    "VOLKSWG": "VOLKSWAGEN",
    "VLKWG": "VOLKSWAGEN",
    "VICTORY": "VICTORY",
    "CHEN": None,
    "ACURASIL": "ACURA",
    "2019": None,
    "PETREBUILD": None,
    "POSH": None,
    "BIKE": None,
    "AUSI": "AUDI",
    "BMWX1": "BMW",
    "ENZ": "MERCEDES-BENZ",
    "INTERNAT": "INTERNATIONAL",
    "TOYT`": "TOYOTA",
    "VNNISSAN": "NISSAN",
    "MITSUBUISHI": "MITSUBISHI",
    "HYUNVAL2012": "HYUNDAI",
    "INFII": "INFINITI",
    "NOVB": None,
    "CHER": "CHEVROLET",
    "CNRY": "TOYOTA",
    "SMARTC": "SMART",
    "HISSAN": "NISSAN",
    "CJRY": "CHRYSLER",
    "NOND": None,
    "AUDIVAL2013": "AUDI",
    "CHYSLYER": "CHRYSLER",
    "JONDA": "HONDA",
    "BMWVAL2007": "BMW",
    "TOUPT": "TOYOTA",
    "RAV 4": "TOYOTA",
    "CHE V": "CHEVROLET",
    "LEXUVAL2011": "LEXUS",
    "FORDM": "FORD",
    "DODGVAL2008": "DODGE",
    "VHEROLET": "CHEVROLET",
    "VOLKSWGN": "VOLKSWAGEN",
    "HARLEY DAV": "HARLEY-DAVIDSON",
    "KIAVAL": "KIA",
    "BRIM": None,
    "TOYTTA": "TOYOTA",
    "TOYITA": "TOYOTA",
    "RAZOR": None,
    "MASTER": None,
    "ANVIL TRAILER": None,
    "FPHT": None,
    "CHEVY TR": "CHEVROLET",
    "SILVERADO": "CHEVROLET",
    "FLYER": None,
    "FORED": "FORD",
    "AUD1": "AUDI",
    "CHRYVAL2011": "CHRYSLER",
    "GMCV": "GMC",
    "ACURUA": "ACURA",
    "MTSBSHI": "MITSUBISHI",
    "ALFAROMEO": "ALFA ROMEO",
    "CADIAC": "CADILLAC",
    "MCIN": None,
    "MAC": None,
    "GILLEG": "GILLIG",
    "HYUNDAP": "HYUNDAI",
    "HONDVAL2002": "HONDA",
    "SMAR": "SMART",
    "RIDE": None,
    "CONT": None,
    "PON": "PONTIAC",
    "RNGRVR": "RANGE ROVER",
    "HYUANDA": "HYUNDAI",
    "MINI C": "MINI",
    "TPOYOTA": "TOYOTA",
    "MASZDA": "MAZDA",
    "DOODGE": "DODGE",
    "OLDSVAL2003": "OLDSMOBILE",
    "INTENATIONAL": "INTERNATIONAL",
    "GC": "GMC",
    "HYUDA": "HYUNDAI",
    "RO VER": "LAND ROVER",
    "VHEVY": "CHEVROLET",
    "IS300LEXUS": "LEXUS",
    "GENE": "GENESIS",
    "IUZU": "ISUZU",
    "LEXUVAL2010": "LEXUS",
    "KRYSTAL": None,
    "BMWVAL1995": "BMW",
    "JYUDAI": "HYUNDAI",
    "VOLVVAL2005": "VOLVO",
    "TAKE": None,
    "LANDVAL2012": "LAND ROVER",
    "BMV": "BMW",
    "BWW": "BMW",
    "HONDM": "HONDA",
    "PETR": "PETERBILT",
    "HONDA 4D": "HONDA",
    "MNNI COOPER": "MINI",
    "1D7HA18D54S7413": None,
    "7BG6353": None,
    "LANDRVR": "LAND ROVER",
    "THOAS": "THOMAS",
    "RIDGE": None,
    "GENUINE": None,
    "MERCVAL1993": "MERCEDES",
    "STR": "STERLING",
    "GIL": "GILLIG",
    "KMCO": "KYMCO",
    "MERCEDEES": "MERCEDES",
    "HYUA": "HYUNDAI",
    "OY": "TOYOTA",
    "FORD FUSION": "FORD",
    "VOLOV": "VOLVO",
    "KOEHRING": None,
    "HYUD": "HYUNDAI",
    "LXUS": "LEXUS",
    "4SCHEVY": "CHEVROLET",
    "VOLLSWAGON": "VOLKSWAGEN",
    "VO;K": "VOLKSWAGEN",
    "SUPE": None,
    "HYUNANDI": "HYUNDAI",
    "GDAN": None,
    "MIREDTS": "MERCEDES",
    "TOYOTA4S": "TOYOTA",
    "CHRYSKER": "CHRYSLER",
    "RANGE RVER": "RANGE ROVER",
    "SARURN": "SATURN",
    "NOSAN": "NISSAN",
    "RAVE": None,
    "LANDROER": "LAND ROVER",
    "ONTL": "INTERNATIONAL",
    "BICYCLE": None,
    "HYNUDAI": "HYUNDAI",
    "TRUCK": None,
    "NXH110": None,
    "ALF": "ALFA ROMEO",
    "GILI": "GILLIG",
    "AUDIO": "AUDI",
    "VOLKS WAGAN": "VOLKSWAGEN",
    "VOLVO`": "VOLVO",
    "THOMAS BUILT": "THOMAS",
    "TR": None,
    "TOYT  SCION": "SCION",
    "DOG": "DODGE",
    "NERCEDEZ": "MERCEDES",
    "FLRD": "FORD",
    "FFORD": "FORD",
    "HOND4S": "HONDA",
    "ACUR TL": "ACURA",
    "GENA": "GENESIS",
    "JIA": None,
    "FD": "FORD",
    "COIN": None,
    "ECON": None,
    "CHEYY": "CHEVROLET",
    "FED EX TK": None,
    "HNODA": "HONDA",
    "HYUNDDIA": "HYUNDAI",
    "KAWAK": "KAWASAKI",
    "ELECTRIC": None,
    "RANGSUV": "RANGE ROVER",
    "NAZDA": "MAZDA",
    "2008": None,
    "TRL": None,
    "MC TRUCK": None,
    "BUI": "BUICK",
    "HYUAN": "HYUNDAI",
    "CHEVRIOLET": "CHEVROLET",
    "DODDE": "DODGE",
    "KYMOCO": "KYMCO",
    "TOYUT": "TOYOTA",
    "HYNUNDAI": "HYUNDAI",
    "UDT": None,
    "AUDIE": "AUDI",
    "H-D": "HARLEY-DAVIDSON",
    "NISSVAL2012": "NISSAN",
    "DESO": None,
    "THOMOS": "TOMOS",
    "HONDA ODYSSEY": "HONDA",
    "LEXUZS": "LEXUS",
    "PTERBILT": "PETERBILT",
    "FORD2006": "FORD",
    "UPS": None,
    "MITTSIBTI": "MITSUBISHI",
    "HYANDIA": "HYUNDAI",
    "4S3BWAG62L30096": None,
    "KAASAKI": "KAWASAKI",
    "DODHE": "DODGE",
    "OLD": "OLDSMOBILE",
    "SSSB": None,
    "LIA": None,
    "CHYRL": "CHRYSLER",
    "TAOATO": "TAO TAO",
    "HYUNUDAI": "HYUNDAI",
    "HONDA2012": "HONDA",
    "HTUN": None,
    "BUCIK": "BUICK",
    "FODD": "FORD",
    "MASR": "MASERATI",
    "FIORD": "FORD",
    "LANDCRU": "TOYOTA",
    "EZ DUMPER": None,
    "ACURVAL1997": "ACURA",
    "BMWVAL2005": "BMW",
    "MERDEDES": "MERCEDES",
    "MIMI": "MINI",
    "AXURA": "ACURA",
    "SUNA": None,
    "MALLARD": None,
    "FREIGHTLINTER": "FREIGHTLINER",
    "VOLVVAL1990": "VOLVO",
    "ACURA TSX": "ACURA",
    "PTRBLT": "PETERBILT",
    "ROCK": None,
    "NWFL": "NEW FLYER",
    "JAGJUAR": "JAGUAR",
    "MITA": "MITSUBISHI",
    "JAUGUAR": "JAGUAR",
    "DODGW": "DODGE",
    "TRASH TK": None,
    "LEXUE": "LEXUS",
    "IINTL": "INTERNATIONAL",
    "NTERNATIONAL": "INTERNATIONAL",
    "QACURA": "ACURA",
    "CHVEROLET": "CHEVROLET",
    "HYUNDA5": "HYUNDAI",
    "LANDR ROVER": "LAND ROVER",
    "AMERICAN": None,
    "VM": None,
    "MRECEDES": "MERCEDES",
    "NISSIAM": "NISSAN",
    "NNISSAN": "NISSAN",
    "19XFA1F58BE0143": None,
    "CHRYSLER 300": "CHRYSLER",
    "SICO": "SCION",
    "TOYOTRA": "TOYOTA",
    "NISSAIN": "NISSAN",
    "LNRV": "LAND ROVER",
    "FORDVAL2013": "FORD",
    "JRTR": None,
    "TOYOTA TK": "TOYOTA",
    "ONDA": "HONDA",
    "AVALON": "TOYOTA",
    "4BB5077": None,
    "ROYAL": "ROYAL ENFIELD",
    "DELFAST": None,
    "SCUR": None,
    "CHRV": "CHEVROLET",
    "FREIGHT TK": "FREIGHTLINER",
    "WOLK": "VOLKSWAGEN",
    "TOYY": "TOYOTA",
    "MER/BENZ": "MERCEDES-BENZ",
    "HYUDIA": "HYUNDAI",
    "TRIUMP": "TRIUMPH",
    "CEVY": "CHEVROLET",
    "AUTC": None,
    "UD DS": None,
    "MAZDVAL2013": "MAZDA",
    "JOND": "HONDA",
    "BUICK VAN": "BUICK",
    "LEXUS 4S": "LEXUS",
    "INTERNATL": "INTERNATIONAL",
    "U HAUL": None,
    "JEEP TK": "JEEP",
    "HYD": "HYUNDAI",
    "COLE": None,
    "SIBARU": "SUBARU",
    "VOLWAGON": "VOLKSWAGEN",
    "SQUINOX": "CHEVROLET",
    "H6NDA": "HONDA",
    "GMZ": "GMC",
    "SUBARUE": "SUBARU",
    "JUGUAR": "JAGUAR",
    "FRTLNER": "FREIGHTLINER",
    "JMH": None,
    "SCIAON": "SCION",
    "GOE": "GEO",
    "UB": None,
    "CAMARO": "CHEVROLET",
    "MERCEDES BNZ": "MERCEDES-BENZ",
    "MERCBEN": "MERCEDES-BENZ",
    "NNISS": "NISSAN",
    "MERZ-BENZ": "MERCEDES-BENZ",
    "MAIL TRUCK": None,
    "RANGROV": "RANGE ROVER",
    "JEPP": "JEEP",
    "ACURAX": "ACURA",
    "HONDVAL2008": "HONDA",
    "APRI": "APRILIA",
    "FRHTLINER": "FREIGHTLINER",
    "1N4BL4BV8KC1872": None,
    "KRAF": None,
    "1G8ZH5282VZ1642": None,
    "HUNDI": "HYUNDAI",
    "HYJN": "HYUNDAI",
    "SPOR": None,
    "HYUNDAIE": "HYUNDAI",
    "4T1BK46K17U0182": None,
    "VOLKVAL2010": "VOLKSWAGEN",
    "POMTIAC": "PONTIAC",
    "CHEVYROLEY": "CHEVROLET",
    "HUYANDAI": "HYUNDAI",
    "CHEVY P": "CHEVROLET",
    "PETERBLT": "PETERBILT",
    "MERCEDEZBENZ": "MERCEDES-BENZ",
    "CYSTLER": "CHRYSLER",
    "BRI-MAR": None,
    "MITSUBISHIT": "MITSUBISHI",
    "CHRRYSLER": "CHRYSLER",
    "SUIZ": "SUZUKI",
    "HMST": None,
    "INTERNTIONAL": "INTERNATIONAL",
    "GNC": "GMC",
    "5XYPKDA59LG6874": None,
    "PLDS": None,
    "JF1GG29624G8084": None,
    "KWANG YANG": "KYMCO",
    "INFITY": "INFINITI",
    "TORY": "TOYOTA",
    "ESCOTL": None,
    "MTSUBISHI": "MITSUBISHI",
    "MERCB": "MERCEDES",
    "TOYOTAQ": "TOYOTA",
    "HONDS": "HONDA",
    "SMARTCAR": "SMART",
    "MERZBEN": "MERCEDES-BENZ",
    "CHEVYQ": "CHEVROLET",
    "NERZ": "MERCEDES",
    "CGEVY": "CHEVROLET",
    "FRGHTLINR": "FREIGHTLINER",
    "EVEREST": "FORD",
    "NIAAN": "NISSAN",
    "MAZDA 3": "MAZDA",
    "LORI": None,
    "MATRIX": "TOYOTA",
    "TOWN N COUNTRY": "CHRYSLER",
    "VHEV": "CHEVROLET",
    "HOOND": "HONDA",
    "NOISSAN": "NISSAN",
    "VOLK WAGON": "VOLKSWAGEN",
    "KIDA": "KIA",
    "MERCUTY": "MERCURY",
    "UNIT": None,
    "MASER": "MASERATI",
    "INFIINTI": "INFINITI",
    "NERCEDES BENZ": "MERCEDES-BENZ",
    "INTL HRVST": "INTERNATIONAL",
    "TOYOTA S": "TOYOTA",
    "MITSBUISHI": "MITSUBISHI",
    "MATL": None,
    "LOTU": "LOTUS",
    "PRTB": "PETERBILT",
    "WESTERN": "WESTERN STAR",
    "TOYUTA": "TOYOTA",
    "PJ": None,
    "HERTZ": None,
    "2HGES26792H5467": None,
    "MERCEDES BENZE": "MERCEDES-BENZ",
    "MRC BENZ": "MERCEDES-BENZ",
    "RODGE": "DODGE",
    "MAYB": "MAYBACH",
    "TOYOVAL2015": "TOYOTA",
    "SONATA": "HYUNDAI",
    "CRHSYLER": "CHRYSLER",
    "FREIG": "FREIGHTLINER",
    "PJTM": None,
    "ICEB": None,
    "MERCEDES-BNZ": "MERCEDES-BENZ",
    "CUST": None,
    "TOYOVAL2002": "TOYOTA",
    "CUT": None,
    "2T3P1RFV9LW1182": None,
    "EZDUMPER": None,
    "INFINITTI": "INFINITI",
    "FUSION": "FORD",
    "SUZUIKI": "SUZUKI",
    "LDRV": "LAND ROVER",
    "SCBFH7ZA7GC0570": None,
    "SUBARYU": "SUBARU",
    "CADII": "CADILLAC",
    "LAD ROVER": "LAND ROVER",
    "PT CRUISER": "CHRYSLER",
    "PLYMOUYH": "PLYMOUTH",
    "MITSVAL2014": "MITSUBISHI",
    "DLR": None,
    "HONDA CIVIC": "HONDA",
    "HONDA ELEMENT": "HONDA",
    "CYRSLER": "CHRYSLER",
    "FRET": "FREIGHTLINER",
    "KENWORK": "KENWORTH",
    "IINFINITI": "INFINITI",
    "VOLVVAL2012": "VOLVO",
    "HONDA9CP5696": "HONDA",
    "TOAY": "TOYOTA",
    "AIDI": "AUDI",
    "MERCEDEZQ": "MERCEDES",
    "HONDACIB=": "HONDA",
    "MASARATTI": "MASERATI",
    "LEXUVAL2004": "LEXUS",
    "3N1CB51D75L5139": None,
    "CVEVROLET": "CHEVROLET",
    "MTS": "MITSUBISHI",
    "MAIL": None,
    "HTUNDAI": "HYUNDAI",
    "OYOYA": "TOYOTA",
    "HONDVAL1998": "HONDA",
    "ACUEA": "ACURA",
    "VALU": None,
    "MERC. BENZ": "MERCEDES-BENZ",
    "LEXUXUS": "LEXUS",
    "JEE": "JEEP",
    "KENMORE": None,
    "BASHAN": None,
    "VOLSWAGO": "VOLKSWAGEN",
    "MAZFA": "MAZDA",
    "TRLK": None,
    "PORCHA": "PORSCHE",
    "TOYOVAL2004": "TOYOTA",
    "HYANDUI": "HYUNDAI",
    "MASERADI": "MASERATI",
    "PEQU": None,
    "PONATIAC": "PONTIAC",
    "ACURVAL1998": "ACURA",
    "FRORD": "FORD",
    "NII": "NISSAN",
    "ICEBEAR": None,
    "TOYOVAL2000": "TOYOTA",
    "VILK": "VOLKSWAGEN",
    "BMWV": "BMW",
    "CHEVRY": "CHEVROLET",
    "NMW": "BMW",
    "MER URY": "MERCURY",
    "ROLL": "ROLLS-ROYCE",
    "ARES": None,
    "CHVEOLET": "CHEVROLET",
    "CORVETTE": "CHEVROLET",
    "DODDGE": "DODGE",
    "KIO": "KIA",
    "BEND": None,
    "RENEGADE": "JEEP",
    "SUZUKI`": "SUZUKI",
    "D & D": None,
    "FORDVAL2008": "FORD",
    "DISCOVERY": "LAND ROVER",
    "VOLSW": "VOLKSWAGEN",
    "I8A": "BMW",
    "MERCU": "MERCURY",
    "CADIL": "CADILLAC",
    "KODIAK": "GMC",
    "FRGT": "FREIGHTLINER",
    "WG": "VOLKSWAGEN",
    "GMEC": "GMC",
    "MRRZ": "MERCEDES",
    "INFINITA": "INFINITI",
    "JRRP": None,
    "MADAZA": "MAZDA",
    "AUDDI": "AUDI",
    "ASTO MARTIN": "ASTON MARTIN",
    "LIC": "LINCOLN",
    "MICR": "NISSAN",
    "INFONITY": "INFINITI",
    "CHRL": "CHRYSLER",
    "BMD": "BMW",
    "VICTORYT": "VICTORY",
    "JP": None,
    "LLEXUS": "LEXUS",
    "KAI": "KIA",
    "CEHEVY": "CHEVROLET",
    "S": None,
    "SGR": None,
    "IKIA": "KIA",
    "HONDA CIVIV": "HONDA",
    "INFIINITI": "INFINITI",
    "MITS.": "MITSUBISHI",
    "2018": None,
    "HUYNDI": "HYUNDAI",
    "YAMAYA": "YAMAHA",
    "MONDA": "HONDA",
    "ARCURA": "ACURA",
    "CADALAC": "CADILLAC",
    "LESXUS": "LEXUS",
    "VOLKWGN": "VOLKSWAGEN",
    "VILKS": "VOLKSWAGEN",
    "CHEK": "CHEVROLET",
    "KIA OPTIMA EX": "KIA",
    "HONODA": "HONDA",
    "US MAIL": None,
    "NYUNDAI": "HYUNDAI",
    "FRHT TK": "FREIGHTLINER",
    "RANGERVR": "RANGE ROVER",
    "MCT": None,
    "INDI": "INDIAN",
    "MERC DODGE": None,
    "FTWD": None,
    "MAXD": "MAZDA",
    "SCENIC VIEW": None,
    "LONGBO": None,
    "YOTOTA": "TOYOTA",
    "CHEVY I": "CHEVROLET",
    "C": None,
    "NISSS": "NISSAN",
    "CHEVROELET": "CHEVROLET",
    "TPYT": "TOYOTA",
    "TTOYTTOYT": "TOYOTA",
    "YOUOTA": "TOYOTA",
    "1HD1KB4179Y6312": None,
    "INFIITI": "INFINITI",
    "THOMAS BUS": "THOMAS",
    "PRIM": None,
    "CAN AM": "CAN-AM",
    "STRATUS": "CHRYSLER",
    "CHRYSLYER": "CHRYSLER",
    "CRYL": "CHRYSLER",
    "MECERDES": "MERCEDES",
    "HONCA": "HONDA",
    "HAYUNDAI": "HYUNDAI",
    "TOYA": "TOYOTA",
    "CHEVVAL1987": "CHEVROLET",
    "CHRYA": "CHRYSLER",
    "FREGHT": "FREIGHTLINER",
    "HYAUNDI": "HYUNDAI",
    "CHEROKEE": "JEEP",
    "SUN": None,
    "HONNDA": "HONDA",
    "SUBAARU": "SUBARU",
    "IFIN": "INFINITI",
    "CEHEVROLET": "CHEVROLET",
    "NISSVAL1999": "NISSAN",
    "HYNI": "HYUNDAI",
    "EEP": "JEEP",
    "INFIVAL": "INFINITI",
    "RIO": "KIA",
    "2019TOYOTA": "TOYOTA",
    "ININITI": "INFINITI",
    "ACIRA": "ACURA",
    "VHEVROLET": "CHEVROLET",
    "ROYC": "ROLLS-ROYCE",
    "NISSI": "NISSAN",
    "CARRYON": None,
    "CHRUSTLER": "CHRYSLER",
    "HYYUNDAI": "HYUNDAI",
    "SUBAVAL2001": "SUBARU",
    "DODGVAL2013": "DODGE",
    "DIODGE": "DODGE",
    "LEON": "SEAT",
    "BRTL": None,
    "TRAILOR": None,
    "CGEV": "CHEVROLET",
    "SATRUN": "SATURN",
    "ATM": None,
    "HONG": "HONDA",
    "2T3F1RFVXLW1187": None,
    "RANGEVROVER": "RANGE ROVER",
    "SUSZ": "SUZUKI",
    "KENALWORTH": "KENWORTH",
    "INFINIY": "INFINITI",
    "NEON": "DODGE",
    "LEXUVAL2006": "LEXUS",
    "C300": "MERCEDES",
    "HUUNDAI": "HYUNDAI",
    "HUCA": None,
    "INFINTE": "INFINITI",
    "US": None,
    "BRIMAR": None,
    "ACRU": "ACURA",
    "-": None,
    "CASI": None,
    "METZ": "MERCEDES",
    "NARD": None,
    "GATO": None,
    "DANG FONG": None,
    "TESTLA": "TESLA",
    "MRC": "MERCEDES",
    "LANDOVER": "LAND ROVER",
    "FREIGHTLIER": "FREIGHTLINER",
    "VOLVO SW": "VOLVO",
    "FIATVAL2012": "FIAT",
    "SW": None,
    "INFINNITY": "INFINITI",
    "MITSUBISGU": "MITSUBISHI",
    "INFININTI": "INFINITI",
    "VOLVA": "VOLVO",
    "KIA OPTIMA": "KIA",
    "GILBERT": None,
    "HIOND": "HONDA",
    "TOYO SUV": "TOYOTA",
    "HONDVAL2012": "HONDA",
    "MURC": "MERCEDES",
    "DODGGE": "DODGE",
    "HONDVAL2004": "HONDA",
    "BMS": "BMW",
    "CHEVORELT": "CHEVROLET",
    "DYKO": None,
    "HYUNVAL2014": "HYUNDAI",
    "DUSSELDORF": None,
    "POTIAC": "PONTIAC",
    "CHEVROLE6T": "CHEVROLET",
    "2003": None,
    "LEXUS 4D": "LEXUS",
    "NISSAN ROGUE": "NISSAN",
    "SUBARO": "SUBARU",
    "HOOONDA": "HONDA",
    "MODEL": None,
    "TOY 2S": "TOYOTA",
    "CADDY": "CADILLAC",
    "POONTIAC": "PONTIAC",
    "KARA": None,
    "LNRVR": "LAND ROVER",
    "HYUNFAI": "HYUNDAI",
    "LND": "LAND ROVER",
    "HYUNNDAI": "HYUNDAI",
    "NISSVAL2005": "NISSAN",
    "KENWORTHY": "KENWORTH",
    "MINICOOP": "MINI",
    "ROGE": "NISSAN",
    "DDGE": "DODGE",
    "DURANGO": "DODGE",
    "ACUAR": "ACURA",
    "CADILLAD": "CADILLAC",
    "SPNR": None,
    "CHEVORLEY": "CHEVROLET",
    "MAZDA 6": "MAZDA",
    "MITUSHISHI": "MITSUBISHI",
    "HUYUN": "HYUNDAI",
    "MURANO": "NISSAN",
    "TOYOVAN": "TOYOTA",
    "CAFILLAC": "CADILLAC",
    "PRCH": "PORSCHE",
    "HONDA ACC": "HONDA",
    "FORTE": "KIA",
    "CHEVOLRET": "CHEVROLET",
    "CHRVEROLET": "CHEVROLET",
    "MERVEDEZ": "MERCEDES",
    "SUBAU": "SUBARU",
    "ACRURA": "ACURA",
    "LINCVAL2002": "LINCOLN",
    "CHEVVAL2004": "CHEVROLET",
    "VENT": None,
    "MITUBISHI`": "MITSUBISHI",
    "CADIVAL2012": "CADILLAC",
    "MITCH": None,
    "VOLKWASGEN": "VOLKSWAGEN",
    "FORDVAL2011": "FORD",
    "VOLKZWAGEN": "VOLKSWAGEN",
    "HNO": "HONDA",
    "MEREC": "MERCEDES",
    "MERZCEDES": "MERCEDES",
    "6FAJ71": None,
    "1G2JB12F6471340": None,
    "ACURAS": "ACURA",
    "SLANTRA": "HYUNDAI",
    "TOYOTA P": "TOYOTA",
    "KWASAKI": "KAWASAKI",
    "CHEVRELOT": "CHEVROLET",
    "JEEP 4DR": "JEEP",
    "TOYOVAL": "TOYOTA",
    "INTERNATIONL": "INTERNATIONAL",
    "HYUNVAL2010": "HYUNDAI",
    "VVOLVO": "VOLVO",
    "MTIS": "MITSUBISHI",
    "POIS": None,
    "GS350": "LEXUS",
    "INFNIITY": "INFINITI",
    "MASDIA": "MAZDA",
    "RABBIT": "VOLKSWAGEN",
    "JAGUVAL1991": "JAGUAR",
    "TOYT/SCION": "SCION",
    "AMMO": None,
    "LAND-ROVER": "LAND ROVER",
    "MITU": "MITSUBISHI",
    "CHEVVY": "CHEVROLET",
    "NAIS": "NISSAN",
    "CADILIC": "CADILLAC",
    "TOYT / SCION": "SCION",
    "OLDSMOBLE": "OLDSMOBILE",
    "VKW": "VOLKSWAGEN",
    "HOCNDA": "HONDA",
    "OLDSMOBLIE": "OLDSMOBILE",
    "IFINI": "INFINITI",
    "IKA": None,
    "NMERX": None,
    "MERZ-BENX": "MERCEDES-BENZ",
    "LAND RVT": "LAND ROVER",
    "TYT": "TOYOTA",
    "VOLVOO": "VOLVO",
    "BMQ": "BMW",
    "OLDSVAL1994": "OLDSMOBILE",
    "INFINIITI": "INFINITI",
    "HCHEV": "CHEVROLET",
    "TOYOTA/SCION": "SCION",
    "MURCARY": "MERCURY",
    "FOORD": "FORD",
    "HOLM": None,
    "2BD3611": None,
    "SUZUKIA": "SUZUKI",
    "VNHL": "VAN HOOL",
    "FORDVAL2007": "FORD",
    "JETAA": "VOLKSWAGEN",
    "CHRTSLER": "CHRYSLER",
    "PONTOAC": "PONTIAC",
    "VILVO": "VOLVO",
    "MISTS": "MITSUBISHI",
    "INFNITI": "INFINITI",
    "PONYIAC": "PONTIAC",
    "TOYOVAL1996": "TOYOTA",
    "MERZADEZ": "MERCEDES",
    "TUT": None,
    "MITSI": "MITSUBISHI",
    "STS": "CADILLAC",
    "MINIVAL2009": "MINI",
    "HEEO": None,
    "CHREVROLET": "CHEVROLET",
    "LICOLIN": "LINCOLN",
    "BIG": None,
    "DEALER": None,
    "TURT": None,
    "VOLVVAL2011": "VOLVO",
    "COACHMEN": None,
    "MITISUBUSHI": "MITSUBISHI",
    "MERCERDES": "MERCEDES",
    "MAZRA": "MAZDA",
    "MERCEDES C300": "MERCEDES",
    "HONDVAL2011": "HONDA",
    "HONDVAL2003": "HONDA",
    "SURB": "SUBARU",
    "JTDKN3DU6A01143": None,
    "ADILLAC": "CADILLAC",
    "CHEVVAL1984": "CHEVROLET",
    "MISTU": "MITSUBISHI",
    "MERCVAL2001": "MERCEDES",
    "NISSVAL2007": "NISSAN",
    "MAZDA3": "MAZDA",
    "LEXUSS": "LEXUS",
    "CHICAGO": None,
    "VOLJS": "VOLKSWAGEN",
    "CHEVRP;ET": "CHEVROLET",
    "MITSUISHI": "MITSUBISHI",
    "VOILKS": "VOLKSWAGEN",
    "VICT": "VICTORY",
    "TOYOVAL1995": "TOYOTA",
    "TOW": None,
    "2013": None,
    "PONTIAN": "PONTIAC",
    "CHEVLORET": "CHEVROLET",
    "APACHE": "CHEVROLET",
    "TOYOTA CL": "TOYOTA",
    "CHEVVAL2003": "CHEVROLET",
    "LEVUS": "LEXUS",
    "HT": None,
    "JOURNEY": "DODGE",
    "HYUNVAL2008": "HYUNDAI",
    "PLYMONTH": "PLYMOUTH",
    "PONTVAL2006": "PONTIAC",
    "CJEV": "CHEVROLET",
    "HTU": None,
    "HUMAN": None,
    "DOGG": "DODGE",
    "VOLKVAL2013": "VOLKSWAGEN",
    "TOYOTQ": "TOYOTA",
    "YTOYOTA": "TOYOTA",
    "TOYOVAL1998": "TOYOTA",
    "VHECY": "CHEVROLET",
    "VOLKSWAON": "VOLKSWAGEN",
    "LES": "LEXUS",
    "HONDVAL2014": "HONDA",
    "INFINTIT": "INFINITI",
    "DLR TAG DODGE": "DODGE",
    "HD CR": "HARLEY-DAVIDSON",
    "COLCO": None,
    "CARY": None,
    "GRAND MARQ": "MERCURY",
    "PONTIACE": "PONTIAC",
    "NEO": None,
    "HONDACRV": "HONDA",
    "CHECROLET": "CHEVROLET",
    "SOSGE": None,
    "SKYL": None,
    "BW": "BMW",
    "HYUNDAIA": "HYUNDAI",
    "GALV": None,
    "KIAVAL2004": "KIA",
    "4RUNNER": "TOYOTA",
    "Q50": "INFINITI",
    "CROS": None,
    "CHRSY": "CHRYSLER",
    "CHRYSLERQ": "CHRYSLER",
    "CONCORDE": "CHRYSLER",
    "GRECH": None,
    "MAZDVAL2011": "MAZDA",
    "BNMW": "BMW",
    "MOBED": None,
    "DODGA": "DODGE",
    "HUUN": "HYUNDAI",
    "VOLSKWAGEN": "VOLKSWAGEN",
    "POLA": "POLARIS",
    "LINNCOLN": "LINCOLN",
    "ITSUBISHI": "MITSUBISHI",
    "WBAHJ6317PGD231": None,
    "AURRA": "ACURA",
    "MITSUBITSHI": "MITSUBISHI",
    "BM": "BMW",
    "HYUNVA": "HYUNDAI",
    "ISUZI": "ISUZU",
    "BMWVAL2003": "BMW",
    "FORDVAL2000": "FORD",
    "MITSUHISHI": "MITSUBISHI",
    "NISSVAL2015": "NISSAN",
    "DODE": "DODGE",
    "BLK": None,
    "VOLCO": "VOLVO",
    "WHTNG": None,
    "MARZ": "MERCEDES",
    "RDX": "ACURA",
    "FORDVAL2006": "FORD",
    "PONTANIC": "PONTIAC",
    "BUIICK": "BUICK",
    "GREAT DANE": None,
    "PNTIAC": "PONTIAC",
    "NODA": "HONDA",
    "VWAGON": "VOLKSWAGEN",
    "INFNTI": "INFINITI",
    "CHYRSLERR": "CHRYSLER",
    "MAZDVAL2007": "MAZDA",
    "TOBR": None,
    "TOTYT": "TOYOTA",
    "MT": None,
    "P4D": None,
    "PONTAIC": "PONTIAC",
    "MERCEADES": "MERCEDES",
    "MZD": "MAZDA",
    "SATARN": "SATURN",
    "ADUI": "AUDI",
    "LAND ROER": "LAND ROVER",
    "INFINITYI": "INFINITI",
    "CHEVC": "CHEVROLET",
    "SABU": "SUBARU",
    "TAURUS": "FORD",
    "CRHY": "CHRYSLER",
    "ROGUENISSAN": "NISSAN",
    "VOLKSSWAGON": "VOLKSWAGEN",
    "HYUNDHI": "HYUNDAI",
    "VWOLK": "VOLKSWAGEN",
    "MER-BENZ": "MERCEDES-BENZ",
    "HUM": "HUMMER",
    "VOLVL": "VOLVO",
    "LANK": None,
    "JEED": "JEEP",
    "WK": None,
    "WABASH": None,
    "X5": "BMW",
    "TRAILER": None,
    "GILLAG": "GILLIG",
    "ISUKU": "ISUZU",
    "MASZ": "MASERATI",
    "INFIITY": "INFINITI",
    "JTDKT4K37B53306": None,
    "HYAUNDAI": "HYUNDAI",
    "SATN": "SATURN",
    "CHRYVAL2004": "CHRYSLER",
    "VOLKA": "VOLKSWAGEN",
    "LEXUVAL1992": "LEXUS",
    "VOLKSEWAGON": "VOLKSWAGEN",
    "DHRY": "CHRYSLER",
    "THRUXTON": "TRIUMPH",
    "TYOYTA": "TOYOTA",
    "SUV": None,
    "JEEPVAL1999": "JEEP",
    "HOMNDA": "HONDA",
    "CHEVL": "CHEVROLET",
    "KYCO": "KYMCO",
    "STAURN": "SATURN",
    "MURERY": "MERCURY",
    "TOPB": None,
    "LA JOLLA": None,
    "HYUNSAI": "HYUNDAI",
    "POLC": "POLARIS",
    "IMPALA": "CHEVROLET",
    "JEEPQ": "JEEP",
    "VOLKSWAGWEN": "VOLKSWAGEN",
    "FODE": "FORD",
    "ACURVAL2008": "ACURA",
    "PREV": None,
    "INIFINTY": "INFINITI",
    "OLDESMOBILE": "OLDSMOBILE",
    "CHIVY": "CHEVROLET",
    "MAZSA": "MAZDA",
    "DODOGE": "DODGE",
    "VOLKVAL2006": "VOLKSWAGEN",
    "SUBBARU": "SUBARU",
    "LINCOLM": "LINCOLN",
    "SUBAVAL1999": "SUBARU",
    "JOOP": "JEEP",
    "LINK": "LINCOLN",
    "MERXZ": "MERCEDES",
    "LEXZ": "LEXUS",
    "WELL": None,
    "PONTVAL2000": "PONTIAC",
    "DORS": "DODGE",
    "CHEVERLET": "CHEVROLET",
    "LEXIU": "LEXUS",
    "SUBAVAL2012": "SUBARU",
    "FIA": "FIAT",
    "VOLKSVAGON": "VOLKSWAGEN",
    "MITSHUBITSHI": "MITSUBISHI",
    "CHEVYY": "CHEVROLET",
    "JANGUAR": "JAGUAR",
    "SUBAVAL2011": "SUBARU",
    "MERCEDES BENX": "MERCEDES-BENZ",
    "CHDVY": "CHEVROLET",
    "NISSANN": "NISSAN",
    "MERCVAL2000": "MERCEDES",
    "PAAM": None,
    "XB": None,
    "1FMEU15H9LLA053": None,
    "ROLS": "ROLLS-ROYCE",
    "VOLKVAL2011": "VOLKSWAGEN",
    "KONA": "HYUNDAI",
    "F150": "FORD",
    "ISUZE": "ISUZU",
    "SUSK": "SUZUKI",
    "HYUUNDAI": "HYUNDAI",
    "CADALLIAC": "CADILLAC",
    "=ACURA": "ACURA",
    "CHEVVAL2005": "CHEVROLET",
    "PLMOUTH": "PLYMOUTH",
    "CADAILLIC": "CADILLAC",
    "CHYSTLER": "CHRYSLER",
    "SAABVAL2010": "SAAB",
    "IZUZ": "ISUZU",
    "NISSANG": "NISSAN",
    "CHRYSELER": "CHRYSLER",
    "INIT": "INFINITI",
    "HOIDNA": "HONDA",
    "VOLKVAL": "VOLKSWAGEN",
    "ORBEA": None,
    "MERCEDES MENZ": "MERCEDES-BENZ",
    "BIKE FRIDAY": None,
    "MERCEDES ENZ": "MERCEDES-BENZ",
    "TNERNATIONAL": "INTERNATIONAL",
    "HEVROLET": "CHEVROLET",
    ",AZDA": "MAZDA",
    "HYUBDAI": "HYUNDAI",
    "SUBAURU": "SUBARU",
    "HYUINDAI": "HYUNDAI",
    "CHRYSLTER": "CHRYSLER",
    "LEXES": "LEXUS",
    "ISUZVAL1998": "ISUZU",
    "LEMUS": "LEXUS",
    "VOLKSWATON": "VOLKSWAGEN",
    "LINVOLN": "LINCOLN",
    "NISSVAL2008": "NISSAN",
    "VOLKSVAGEN": "VOLKSWAGEN",
    "CHEVRLO": "CHEVROLET",
    "FHT": "FREIGHTLINER",
    "TESLLA": "TESLA",
    "MOTZ": None,
    "HONFA": "HONDA",
    "A URA": "ACURA",
    "MERCVAL2014": "MERCEDES",
    "ESCAPE": "FORD",
    "HONSA": "HONDA",
    "SUBARUA": "SUBARU",
    "INTI": "INFINITI",
    "SUARU": "SUBARU",
    "SCOTT": None,
    "3FA6P0G75ER3736": None,
    "TAM": None,
    "MERCEDES BANZ": "MERCEDES-BENZ",
    "NIDDAN": "NISSAN",
    "4T1BE32K95U0427": None,
    "NITS": "NISSAN",
    "CADA": "CADILLAC",
    "TOY  SC": "SCION",
    "SUBURI": "SUBARU",
    "ACURVAL1996": "ACURA",
    "CADI4S": "CADILLAC",
    "5BL2341": None,
    "TOY SCION": "SCION",
    "MUR": None,
    "SUZKI": "SUZUKI",
    "CHEROVET": "CHEVROLET",
    "CHEVRLOET": "CHEVROLET",
    "CADIVAL2006": "CADILLAC",
    "2015": None,
    "HYNU": "HYUNDAI",
    "HONDVAL2015": "HONDA",
    "SATURNI": "SATURN",
    "VOLKSWGAN": "VOLKSWAGEN",
    "SABLE": "MERCURY",
    "NUISSAN": "NISSAN",
    "CHHEVROLET": "CHEVROLET",
    "HONGA": "HONDA",
    "TOYOVAL1992": "TOYOTA",
    "WRANGLER": "JEEP",
    "KIAVAL2005": "KIA",
    "TOYOVAL2003": "TOYOTA",
    "PLY": "PLYMOUTH",
    "TRAI": None,
    "8NFINITI": "INFINITI",
    "VOLKSWAHEN": "VOLKSWAGEN",
    "B,W": "BMW",
    "FOCUS": "FORD",
    "PONTIACC": "PONTIAC",
    "EMGAUDI": "AUDI",
    "BBUICK": "BUICK",
    "SUBAVAL2006": "SUBARU",
    "VAN": None,
    "VVOLKSWAGEN": "VOLKSWAGEN",
    "TOYOVAL1991": "TOYOTA",
    "ACCO": "HONDA",
    "MBY": "BMW",
    "SUSKI": "SUZUKI",
    "VOLT": "CHEVROLET",
    "SXION": "SCION",
    "HUDAYI": "HYUNDAI",
    "SCIN": "SCION",
    "NISSAV": "NISSAN",
    "MERCVAL2004": "MERCEDES",
    "OLKSWAGON": "VOLKSWAGEN",
    "GODGE": "DODGE",
    "TEXA": None,
    "HYUNVAL2015": "HYUNDAI",
    "MIAZDA": "MAZDA",
    "VOLKSWAGAON": "VOLKSWAGEN",
    "DODGVAL2000": "DODGE",
    "CR-V": "HONDA",
    "DUDGE": "DODGE",
    "NAVI": None,
    "ION": "SATURN",
    "VVW": "VOLKSWAGEN",
    "MERCVAL2011": "MERCEDES",
    "BIKTRIS": None,
    "DODGVAL2012": "DODGE",
    "ICU": None,
    "SUBIE": "SUBARU",
    "CADDILIAC": "CADILLAC",
    "AQCURA": "ACURA",
    "INFINITIE": "INFINITI",
    "HARI": "HARLEY-DAVIDSON",
    "DODGVAL1998": "DODGE",
    "VOLKCSWAGON": "VOLKSWAGEN",
    "MISTBUSHI": "MITSUBISHI",
    "CRV": "HONDA",
    "HYYNDAI": "HYUNDAI",
    "WILKSWAGON": "VOLKSWAGEN",
    "1FTFW1RG6LFB842": None,
    "CHYRLER": "CHRYSLER",
    "MEC": "MERCEDES",
    "MITSHIBI": "MITSUBISHI",
    "3VW4T7AU1GM0162": None,
    "HNHONDA": "HONDA",
    "CHRYST": "CHRYSLER",
    "FOROD": "FORD",
    "DONDE": "DODGE",
    "EXPRESS": "CHEVROLET",
    "HIUDAI": "HYUNDAI",
    "LECXUS": "LEXUS",
    "CHEV1": "CHEVROLET",
    "HYUH": "HYUNDAI",
    "VOLK WAGAN": "VOLKSWAGEN",
    "CARG": None,
    "HUYUNDI": "HYUNDAI",
    "SSA": "SAAB",
    "GENSIS": "GENESIS",
    "MITISHBI": "MITSUBISHI",
    "TOYOTA2": "TOYOTA",
    "NIRO": "KIA",
    "HONDACAMRY": "TOYOTA",
    "SUBACA": "SUBARU",
    "SALCJ2FX7LH8453": None,
    "BUIIK": "BUICK",
    "CURA": "ACURA",
    "HAYUNDI": "HYUNDAI",
    "NNT": None,
    "CHRYSLER": "CHRYSLER",
    "INIFITY": "INFINITI",
    "3N1AB7AP7JL6406": None,
    "MITSUBHI": "MITSUBISHI",
    "VOLVVAL2006": "VOLVO",
    "EVOQUE": "LAND ROVER",
    "JUAG": "JAGUAR",
    "ISSZU": "ISUZU",
    "9DP1693": None,
    "JTMRFREV2JD2350": None,
    "TAO MOTOR": "TAO TAO",
    "TMC": "TOYOTA",
    "HYUB": "HYUNDAI",
    "MEB": "MERCEDES",
    "MERCEDES- BENZ": "MERCEDES-BENZ",
    "SUBAEU": "SUBARU",
    "VOLZ": "VOLVO",
    "VOLKS W": "VOLKSWAGEN",
    "MITSHIBISHI": "MITSUBISHI",
    "TOYOT A": "TOYOTA",
    "MITBUBISHI": "MITSUBISHI",
    "SICION": "SCION",
    "VLOKS": "VOLKSWAGEN",
    "VOLT WAGON": "VOLKSWAGEN",
    "DDDGE": "DODGE",
    "WINNA": None,
    "NISSANO": "NISSAN",
    "1FMCU0G70GUB534": None,
    "LXS": "LEXUS",
    "180": None,
    "NISSION": "NISSAN",
    "NISSSN": "NISSAN",
    "CRSY": "CHRYSLER",
    "JM3KE4CY2G06876": None,
    "PORSHCE": "PORSCHE",
    "JTMA1RFV3KJ0132": None,
    "BOLT": "CHEVROLET",
    "CRYSER": "CHRYSLER",
    "WOLKS WAGON": "VOLKSWAGEN",
    "1N4AL3AP3FC5890": None,
    "AC": "ACURA",
    "VERSA": "NISSAN",
    "5NPD84LF6HH0198": None,
    "MITSUBOSHI": "MITSUBISHI",
    "CADILLLAC": "CADILLAC",
    "TOWN AND COUNTR": "CHRYSLER",
    "HUUDAI": "HYUNDAI",
    "MIZZ": None,
    "SHSRD78555U3365": None,
    "LEXXS": "LEXUS",
    "VOLTWAGON": "VOLKSWAGEN",
    "FJ CRUISER": "TOYOTA",
    "HARLY D": "HARLEY-DAVIDSON",
    "INFINITU": "INFINITI",
    "NPR": "ISUZU",
    "HIUNDA": "HYUNDAI",
    "1D7HA18N56J1034": None,
    "MAZDA6": "MAZDA",
    "5YMKT6C31H0U395": None,
    "MITSHIBSHI": "MITSUBISHI",
    "YUK": None,
    "4CD1022": None,
    "MERZEDES BENZ": "MERCEDES-BENZ",
    "VOLVOT": "VOLVO",
    "TRACTOR": None,
    "GMT": "GMC",
    "INIFNITI": "INFINITI",
    "DOGD": "DODGE",
    "M": None,
    "VOLKWAGE": "VOLKSWAGEN",
    "SUBARI": "SUBARU",
    "VOLKSWAGOM": "VOLKSWAGEN",
    "JTMRWRFV1LD0704": None,
    "MITISHIBSHI": "MITSUBISHI",
    "HUNDA": "HYUNDAI",
    "CHEVROLER": "CHEVROLET",
    "MITUBISH": "MITSUBISHI",
    "CADAILAC": "CADILLAC",
    "FLAT": "FIAT",
    "MISHIBISHI": "MITSUBISHI",
    "MITIBSHI": "MITSUBISHI",
    "1VWBN7A37DC0970": None,
    "CHEVROLTE": "CHEVROLET",
    "MERCEDIES": "MERCEDES",
    "CGEVORLET": "CHEVROLET",
    "JH4CU26609C0350": None,
    "1HGFA16516L0589": None,
    "VOLKSWAGGO": "VOLKSWAGEN",
    "CHEVRLETTE": "CHEVROLET",
    "VOLSWAGGEN": "VOLKSWAGEN",
    "NISSVAL2013": "NISSAN",
    "LEXUVAL2008": "LEXUS",
    "5NPD84LF9HH0607": None,
    "SIZUKI": "SUZUKI",
    "NISSIA": "NISSAN",
    "SU": "SUBARU",
    "3N1CE2CP0JL3564": None,
    "NOZDA": "MAZDA",
    "AGA": None,
    "1FTVX12596NB720": None,
    "SIENNA": "TOYOTA",
    "CADIALLIC": "CADILLAC",
    "L ROVER": "LAND ROVER",
    "HIYUNDA": "HYUNDAI",
    "HYDUNAI": "HYUNDAI",
    "MITSUBISHO": "MITSUBISHI",
    "JWWP": "JEEP",
    "2T1BU4EE3CC8369": None,
    "ABY": None,
    "HOYUNDAI": "HYUNDAI",
    "CHONGQING": None,
    "MERCEDY": "MERCEDES",
    "KICKS": "NISSAN",
    "TOWN CAR": "LINCOLN",
    "PONTVAL2001": "PONTIAC",
    "NISSANE": "NISSAN",
    "CADAL": "CADILLAC",
    "PLYMITH": "PLYMOUTH",
    "2BZ4372": None,
    "SATURN`": "SATURN",
    "SABURU": "SUBARU",
    "MITISHIBHI": "MITSUBISHI",
    "CHEVROLET`": "CHEVROLET",
    "330I": "BMW",
    "SUBAI": "SUBARU",
    "MSP": None,
    "MITSUBITU": "MITSUBISHI",
    "VIOLKS": "VOLKSWAGEN",
    "MITZL": None,
    "JEER": "JEEP",
    "ACUURA": "ACURA",
    "ACYR": "ACURA",
    "ALABAMA": None,
    "4T1BF22K3YU1039": None,
    "WOLKS": "VOLKSWAGEN",
    "HOLDA": "HONDA",
    "CRYSL": "CHRYSLER",
    "AMTI": None,
    "TUCSON": "HYUNDAI",
    "VOLKWAGGEN": "VOLKSWAGEN",
    "INIFINTI": "INFINITI",
    "JEEDP": "JEEP",
    "CADU": "CADILLAC",
    "TECTRON": None,
    "CIVC": "HONDA",
    "FORD CROWN VIC": "FORD",
    "VLV": "VOLVO",
    "CLUB CAR": None,
    "FORDVAL2012": "FORD",
    "APRILLIA": "APRILIA",
    "LEXUCS": "LEXUS",
    "RALLY": None,
    "ALPHA ROMEO": "ALFA ROMEO",
    "MERZZ": "MERCEDES",
    "NUWA": None,
    "DODGVAL2003": "DODGE",
    "VWMAZDA": None,
    "FORG": "FORD",
    "CHEVORLETT": "CHEVROLET",
    "CEHEV": "CHEVROLET",
    "HONDASILVER": "HONDA",
    "VNTO": None,
    "POINT": None,
    "VOLKSWAGEG": "VOLKSWAGEN",
    "HIGHLANDER": "TOYOTA",
    "EZGO": None,
    "HONDVAL2009": "HONDA",
    "V0LKSWAGEN": "VOLKSWAGEN",
    "RUKUS": None,
    "A4": "AUDI",
    "INFNI": "INFINITI",
    "CHEVORLETE": "CHEVROLET",
    "ACORA": "ACURA",
    "NISSAN ALTIMA": "NISSAN",
    "GRAND CHER": "JEEP",
    "PLMTH": "PLYMOUTH",
    "TOYT=OTA": "TOYOTA",
    "FODR": "FORD",
    "AUI": "AUDI",
    "HOIND": "HONDA",
    "MITSUBISHII": "MITSUBISHI",
    "TO": "TOYOTA",
    "BRINKS": None,
    "HYUNVAL2005": "HYUNDAI",
    "ARI": None,
    "FISR": None,
    "MOTORCYCLE": None,
    "TOPT": None,
    "YONG": None,
    "BLUBIRD": "NISSAN",
    "TRAC": None,
    "KN TELURIDE": "KIA",
    "NVAE": None,
    "HAULMARK": None,
    "LNDROV": "LAND ROVER",
    "RANGE ROVE": "RANGE ROVER",
    "CRHYSLER": "CHRYSLER",
    "CARRY-ON": None,
    "MTRA": None,
    "TENERE": "YAMAHA",
    "MTZR": None,
    "SANMAN COUNTY": None,
    "VOLOVO": "VOLVO",
    "CHRY7SLER": "CHRYSLER",
    ",EXUS": "LEXUS",
    "TSELA": "TESLA",
    "JIAJE": None,
    "VOLLKS": "VOLKSWAGEN",
    "PLSR": "POLARIS",
    "AQUT": "ACURA",
    "ARII": None,
    "NOVA": "CHEVROLET",
    "VENOM": None,
    "MEXD": "MERCEDES",
    "TAZHOU": None,
    "MERCECES": "MERCEDES",
    "ZSTV": None,
    "LNCOLIN": "LINCOLN",
    "ZNEL": None,
    "RANGE ROVERLNDR": "LAND ROVER",
    "CAT": None,
    "CHEVROILET": "CHEVROLET",
    "SWAGEN": "VOLKSWAGEN",
    "CHVEROLT": "CHEVROLET",
    "TAZIHOU": None,
    "PTRBUILT": "PETERBILT",
    "OLNEY": None,
    "CHMM": None,
    "X3": "BMW",
    "SUUBARU": "SUBARU",
    "HIUDAY": "HYUNDAI",
    "KAWAZAKI": "KAWASAKI",
    "SURETRAC": None,
    "UDUM": None,
    "ME/BZ": "MERCEDES-BENZ",
    "E430": "MERCEDES",
    "POBNTIAC": "PONTIAC",
    "TESLA MOTORS": "TESLA",
    "POLE": "POLARIS",
    "CYBERTRUCK": "TESLA",
    "SKAM": None,
    "RAM PICK UP": "RAM",
    "ZHEJIANG SHANQI": None,
    "COLKSWAGON": "VOLKSWAGEN",
    "LUCD": "LUCID",
    "WINN": None,
    "TRUM": None,
    "SUBA5RU": "SUBARU",
    "MAZARATTI": "MASERATI",
    "MERZ-BZ": "MERCEDES-BENZ",
    "SUNS": None,
    "FREIGTLIN": "FREIGHTLINER",
    "NFLY": "NEW FLYER",
    "TESLAY": "TESLA",
    "ZOUZHILONG TECH": None,
    "ZHEJ": None,
    "EKO": None,
    "TES3A": "TESLA",
    "TAIZHOU ZHONG": None,
    "MAXX": None,
    "SUBUARA": "SUBARU",
    "MARSHAL": None,
    "2020": None,
    "STAN": None,
    "TESA": "TESLA",
    "TOYOTA RAV 4": "TOYOTA",
    "HUNAY": "HYUNDAI",
    "FLYING WING": None,
    "BUICFK": "BUICK",
    "VOLKSWAGOB": "VOLKSWAGEN",
    "BRRN": None,
    "TESAL": "TESLA",
    "TELSA`": "TESLA",
    "COTTRELL": None,
    "JIANGSU": None,
    "SPARK": "CHEVROLET",
    "CARMATE": None,
    "DODGER": "DODGE",
    "FORD FREESTYLE": "FORD",
    "ALUM": None,
    "MEREDEZ": "MERCEDES",
    "WOLKSW": "VOLKSWAGEN",
    "GMCAY": "GMC",
    "POSCHE": "PORSCHE",
    "VENUE": "HYUNDAI",
    "WESTERN-STAR": "WESTERN STAR",
    "MRECEDEZ": "MERCEDES",
    "GHONDA": "HONDA",
    "JUNG": None,
    "GIUP": None,
    "YAMAMA": "YAMAHA",
    "LUXU": "LEXUS",
    "AZDA": "MAZDA",
    "MERCDEZ": "MERCEDES",
    "ZHEN": None,
    "VOLKVWAGON": "VOLKSWAGEN",
    "TOYOTD": "TOYOTA",
    "GENIS": "GENESIS",
    "VOLKSAWGEN": "VOLKSWAGEN",
    "ZHENG": None,
    "LAND5ROVER": "LAND ROVER",
    "FRIEGHT": "FREIGHTLINER",
    "BMWQ": "BMW",
    "OTA": "TOYOTA",
    "FOIRD": "FORD",
    "HONE": "HONDA",
    "KUA": None,
    "CYBER TK": "TESLA",
    "SYBARU": "SUBARU",
    "NFINITI": "INFINITI",
    "SYMG": None,
    "ZERO": None,
    "TESULA": "TESLA",
    "GLC 300": "MERCEDES",
    "RIVAN": "RIVIAN",
    "VOLKAWGEN": "VOLKSWAGEN",
    "FLYWHEEL": None,
    "VOKLKSWAGON": "VOLKSWAGEN",
    "`NISSAN": "NISSAN",
    "PRUIS": "TOYOTA",
    "HONDRA": "HONDA",
    "CIMC": None,
    "ROLLS ROYCE": "ROLLS-ROYCE",
    "MERCEDES BENZ": "MERCEDES-BENZ",
    "HARLEY DAVIDSON": "HARLEY-DAVIDSON"
}

def get_mappings(): return mappings